// graph/plans/plan-v1.1-maverick.cypher
// Source of truth for :Plan {node_id:'plan-v1.1-maverick'} and its WorkItems.
// Idempotent — every write is MERGE + SET. Re-running produces identical graph state.
// Applied by: maverick-autodeploy-{dev,prod}.service (post wi-gs-02) OR
//             maverick-dev apply graph/plans/plan-v1.1-maverick.cypher --target <env>
//
// DO NOT edit this file in-graph directly. Edit here, PR, merge, let autodeploy reconcile.
// Direct writes will be reverted on next manifest reapply (wi-gs-07).

// ============================================================================
// :Plan root
// ============================================================================
MERGE (p:Plan {node_id: 'plan-v1.1-maverick'})
SET p.name = 'plan-v1.1-maverick',
    p.title = 'v1.1 — maverick rebrand, target naming, query tracing, contributor guide SoT, seamless local fork, graph sync + repo-as-SoT',
    p.status = 'proposed',
    p.created_at = datetime('2026-04-20T16:20:00Z'),
    p.updated_at = datetime('2026-04-20T17:00:00Z'),
    p.owner = 'kshitiz',
    p.supersedes = 'plan-onboarding-binary-tdd',
    p.repo = 'Qubit-Capital/maverick',
    p.plan_doc = 'docs/plan-v1.1-maverick.md',
    p.estimated_hours = 53.5,
    p.tracks = ['A-rebrand','B-naming','C-querytrace','D-contributor-guide','E-local-fork','F-ux-tests','G-graph-sync-sot'],
    p.project = 'maverick';

// ============================================================================
// :Track nodes
// ============================================================================
UNWIND [
  {id:'track-A', letter:'A', title:'Rebrand mycelium→maverick (Path A hard fork)', hours:7},
  {id:'track-B', letter:'B', title:'Target naming (maverick-dev / maverick-local)', hours:2.5},
  {id:'track-C', letter:'C', title:'Graph-native QueryTrace', hours:7},
  {id:'track-D', letter:'D', title:'ContributorGuide as graph SoT + md projection', hours:7},
  {id:'track-E', letter:'E', title:'Local fork UX (Docker Compose, Win+Mac seamless)', hours:8},
  {id:'track-F', letter:'F', title:'UX test harness (TDD, 3 personas, CI-gated)', hours:10},
  {id:'track-G', letter:'G', title:'Graph sync + repo-as-SoT', hours:10}
] AS t
MERGE (tr:Track {node_id: t.id})
SET tr.letter = t.letter, tr.title = t.title, tr.estimated_hours = t.hours, tr.project='maverick', tr.plan='plan-v1.1-maverick'
WITH tr
MATCH (p:Plan {node_id:'plan-v1.1-maverick'})
MERGE (p)-[:HAS_TRACK]->(tr);

// ============================================================================
// :WorkItem nodes (all tracks)
// ============================================================================
UNWIND [
  // Track A — Rebrand
  {id:'wi-rb-01', track:'track-A', type:'impl', title:'Move cmd/mycelium/ → cmd/maverick/; update module + imports', acceptance:'go test ./... green; go build -o /tmp/maverick ./cmd/maverick && /tmp/maverick version prints "maverick dev"', deps:[]},
  {id:'wi-rb-02', track:'track-A', type:'impl', title:'Rebrand user-facing strings + config + env vars (MYCELIUM_*→MAVERICK_*)', acceptance:'maverick help has zero mycelium refs; ~/.maverick/ config dir; old env vars accepted with deprecation warning', deps:['wi-rb-01']},
  {id:'wi-rb-03', track:'track-A', type:'impl', title:'Rename release artifacts (goreleaser → maverick_*.tar.gz)', acceptance:'goreleaser build --snapshot produces maverick_* artifacts; no mycelium_* anywhere', deps:['wi-rb-01']},
  {id:'wi-rb-04', track:'track-A', type:'impl', title:'Rewrite installers (install.sh/install.ps1 → ~/.maverick/bin/maverick)', acceptance:'fresh bash install.sh produces working maverick on PATH; zero mycelium on disk', deps:['wi-rb-03']},
  {id:'wi-rb-05', track:'track-A', type:'impl', title:'Rename mycelium-dev bash toolchain → maverick-dev', acceptance:'maverick bootstrap dispatches to maverick-dev bootstrap from fresh clone', deps:['wi-rb-02']},
  {id:'wi-rb-06', track:'track-A', type:'infra', title:'Rename pulse services: mycelium-{smoke,embed,autodeploy-dev} → maverick-*; /opt paths too', acceptance:'systemctl list-units maverick-* all green; mycelium-* empty; smoke/embed/autodeploy functional', deps:['wi-rb-03','wi-rb-04']},
  {id:'wi-rb-07', track:'track-A', type:'docs', title:'Rebrand all teammate-facing docs (README, AGENTS, CLAUDE, MYCELIUM→MAVERICK.md, etc)', acceptance:'rg -l -i mycelium returns only upstream-ref + historical reflections + translator script', deps:['wi-rb-02']},
  {id:'wi-rb-08', track:'track-A', type:'tooling', title:'scripts/translate-upstream.sh — sed-based rename for upstream syncs', acceptance:'runs against kagrawal29/mycelium:main, produces clean rebased branch', deps:['wi-rb-07']},
  {id:'wi-rb-09', track:'track-A', type:'release', title:'Tag + publish v1.1.0', acceptance:'gh release view v1.1.0 published; fresh install on Win/Mac/Linux succeeds', deps:['wi-rb-01','wi-rb-02','wi-rb-03','wi-rb-04','wi-rb-05','wi-rb-06','wi-rb-07','wi-rb-08']},
  // Track B — Target naming
  {id:'wi-nt-01', track:'track-B', type:'impl', title:'--target accepts maverick-{dev,prod,staging,local} with short-name aliases + deprecation warning', acceptance:'both forms work; old form emits one-line warning per session', deps:['wi-rb-02']},
  {id:'wi-nt-02', track:'track-B', type:'infra', title:'Rename pulse neo4j.service → neo4j-prod.service for symmetry', acceptance:'systemctl status neo4j-prod green; bolt-proxy-prod still reaches it; dev/staging unaffected', deps:['wi-rb-06']},
  {id:'wi-nt-03', track:'track-B', type:'docs', title:'All doc examples use maverick-dev/maverick-local; "the maverick graph" as noun', acceptance:'rg for --target (dev|local|prod|staging) returns only deprecation-note files', deps:['wi-nt-01','wi-rb-07']},
  // Track C — QueryTrace
  {id:'wi-qt-01', track:'track-C', type:'graph-write', title:':QueryTrace schema + constraints + indexes on maverick-dev + maverick-prod', acceptance:'SHOW INDEXES shows new; dup-insert fires constraint', deps:[]},
  {id:'wi-qt-02', track:'track-C', type:'infra', title:'maverick-trace.service on pulse :7702 (Python, mirrors embed-proxy shape)', acceptance:'POST /trace returns 204; invalid 400; over-rate 429; :QueryTrace visible via MATCH', deps:['wi-qt-01']},
  {id:'wi-qt-03', track:'track-C', type:'impl', title:'internal/trace client package; fire-and-forget; wraps ask/shell/health/status/doctor; MAVERICK_TRACE=0 opt-out', acceptance:'unit tests green; 100 queries → ≥95 traces land; opt-out produces zero traces', deps:['wi-qt-02','wi-rb-02']},
  {id:'wi-qt-04', track:'track-C', type:'graph-write', title:'Retention: :Invariant + :Protocol prune :QueryTrace > 90d nightly via APOC', acceptance:'insert 100d-old trace; run protocol; gone. invariant visible in maverick health', deps:['wi-qt-01']},
  {id:'wi-qt-05', track:'track-C', type:'graph-write', title:'Canonical analytics queries as :QueryAtom', acceptance:'maverick ask "who queries the graph most" routes + returns', deps:['wi-qt-03']},
  // Track D — ContributorGuide SoT
  {id:'wi-cg-01', track:'track-D', type:'graph-write', title:':ContributorGuide + :GuideSection schema with HAS_SECTION + REFERENCES edges', acceptance:'schema applied on dev+prod; constraint violations tested', deps:[]},
  {id:'wi-cg-02', track:'track-D', type:'graph-write', title:'Seed 8-12 :GuideSection nodes from CONTRIBUTING.md; wire REFERENCES to invariants', acceptance:'MATCH (g:ContributorGuide)-[:HAS_SECTION]->(s) RETURN ordered sections', deps:['wi-cg-01']},
  {id:'wi-cg-03', track:'track-D', type:'impl', title:'maverick export-guide verb — graph → CONTRIBUTING.md', acceptance:'export matches current post-seed; round-trip diff visible', deps:['wi-cg-02','wi-rb-02']},
  {id:'wi-cg-04', track:'track-D', type:'ci', title:'CI drift check: export diff vs committed, fail if different', acceptance:'intentional desync → red; sync → green', deps:['wi-cg-03']},
  {id:'wi-cg-05', track:'track-D', type:'impl', title:'maverick-dev ingest-guide — md → Cypher patch', acceptance:'edit md → ingest → diff matches; PR auto-attaches Cypher', deps:['wi-cg-03']},
  {id:'wi-cg-06', track:'track-D', type:'docs', title:'Docs point at maverick ask "how do I contribute" as primary', acceptance:'returns top 2-3 sections; README explicit about SoT', deps:['wi-cg-05','wi-rb-07']},
  // Track E — Local fork UX
  {id:'wi-lf-01', track:'track-E', type:'impl', title:'deploy/local/docker-compose.yml — neo4j+APOC+ollama+embed-proxy with named volume', acceptance:'docker compose up -d; 3 services healthy in 90s; bolt + embed reachable', deps:['wi-rb-05']},
  {id:'wi-lf-02', track:'track-E', type:'impl', title:'maverick local bootstrap — Docker check → compose up → health-wait → seed :Being', acceptance:'fresh laptop with only Docker Desktop → queryable local graph', deps:['wi-lf-01','wi-rb-02']},
  {id:'wi-lf-03', track:'track-E', type:'impl', title:'maverick local teardown [--delete-data] + maverick local status', acceptance:'up→teardown→up preserves data; --delete-data wipes clean', deps:['wi-lf-02']},
  {id:'wi-lf-04', track:'track-E', type:'impl', title:'maverick fork maverick-dev — APOC export/import into :ForkRecord', acceptance:'fresh bootstrap → fork <2min; node count matches', deps:['wi-lf-02','wi-rb-02']},
  {id:'wi-lf-05', track:'track-E', type:'test', title:'Verify on Win11 + Docker Desktop (no WSL)', acceptance:'10-min walkthrough recorded; docs/windows-local-fork.md', deps:['wi-lf-02','wi-lf-04']},
  {id:'wi-lf-06', track:'track-E', type:'test', title:'Verify on macOS (arm64 + amd64)', acceptance:'docs/mac-local-fork.md with verified commands', deps:['wi-lf-02','wi-lf-04']},
  {id:'wi-lf-07', track:'track-E', type:'docs', title:'Integrate contributor-mode path into README + AGENTS + setup-team.sh', acceptance:'teammate docs show clean binary→local→fork→write→PR', deps:['wi-lf-05','wi-lf-06']},
  // Track F — UX tests (TDD, land RED first)
  {id:'wi-ux-01', track:'track-F', type:'test', title:'test/ux/persona-{reader,contributor,maintainer}.sh on CI Ubuntu/macOS/Windows', acceptance:'all RED before Track A; all GREEN before v1.1.0', deps:[]},
  {id:'wi-ux-02', track:'track-F', type:'test', title:'Time-budget assertions (Reader <5min, Contributor <10min, fork <2min, bootstrap <2min)', acceptance:'regression fails build', deps:['wi-ux-01']},
  {id:'wi-ux-03', track:'track-F', type:'test', title:'Zero-deps: Reader green in alpine+gh+bash+curl+tar only', acceptance:'green in minimal container; dep leak fails', deps:['wi-ux-01']},
  {id:'wi-ux-04', track:'track-F', type:'test', title:'Windows-native: windows-latest runner, no WSL; install.ps1 verified', acceptance:'Windows reader green; WSL detector fires if WSL creeps in', deps:['wi-ux-01']},
  {id:'wi-ux-05', track:'track-F', type:'test', title:'Fork golden: fidelity ≥99.9% against dev', acceptance:'fidelity green; intentional drop caught', deps:['wi-lf-04']},
  {id:'wi-ux-06', track:'track-F', type:'test', title:'Contribution round-trip: graph-edit → export → ingest → identical Cypher', acceptance:'round-trip green; tampering caught by drift check', deps:['wi-lf-04','wi-cg-05']},
  {id:'wi-ux-07', track:'track-F', type:'test', title:'Trace visibility: after ask, :QueryTrace appears in ≤5s', acceptance:'visibility green; MAVERICK_TRACE=0 zero traces', deps:['wi-qt-03']},
  {id:'wi-ux-08', track:'track-F', type:'test', title:'Docs+graph+tests agree — :UXJourney walk', acceptance:'drift between 3 sources fails test', deps:['wi-cg-02']},
  {id:'wi-ux-09', track:'track-F', type:'test', title:'Fresh-pull-preserves-work: 50 local-namespaced nodes survive sync', acceptance:'sync green; no conflict; backup exists', deps:['wi-gs-03']},
  {id:'wi-ux-10', track:'track-F', type:'test', title:'PR round-trip: local edit → export-diff → PR → CI → merge → autodeploy → staging matches', acceptance:'round-trip green; CREATE-without-MERGE caught by CI', deps:['wi-gs-04','wi-gs-05','wi-gs-02']},
  {id:'wi-ux-11', track:'track-F', type:'test', title:'Version switch: create/list/checkout/delete snapshots in <2s each', acceptance:'counts match per snapshot; no bleed between snapshots', deps:['wi-gs-06']},
  {id:'wi-ux-12', track:'track-F', type:'test', title:'Drift healing: rogue write detected + healed within 60s; :DriftEvent logged', acceptance:'rogue node removed; drift event visible', deps:['wi-gs-07']},
  {id:'wi-ux-13', track:'track-F', type:'test', title:'Admin writes forbidden: team user rejected direct; admin succeeds', acceptance:'permission denied with clear error; admin works; no false positives', deps:['wi-gs-08']},
  // Track G — Graph sync + repo-as-SoT
  {id:'wi-gs-01', track:'track-G', type:'tooling', title:'Define graph/ directory structure + graph/manifest.yaml + docs', acceptance:'manifest parses; every .cypher listed; apply-manifest --dry-run prints ordered plan', deps:['wi-rb-07']},
  {id:'wi-gs-02', track:'track-G', type:'infra', title:'maverick-autodeploy-dev idempotent-reapply from graph/; 2-min timer', acceptance:'manual drift → :DriftEvent within 2min → node gone after reapply', deps:['wi-gs-01','wi-rb-06']},
  {id:'wi-gs-03', track:'track-G', type:'impl', title:'maverick local sync --from maverick-dev — backup+partition+reapply+relayer', acceptance:'UX test wi-ux-09 green', deps:['wi-lf-02','wi-gs-01']},
  {id:'wi-gs-04', track:'track-G', type:'impl', title:'maverick-dev diff + export-diff — graph delta → idempotent .cypher', acceptance:'edit 3 nodes → export → re-apply produces same delta, zero other drift', deps:['wi-gs-01','wi-rb-02']},
  {id:'wi-gs-05', track:'track-G', type:'ci', title:'CI graph gate: scratch Neo4j + apply manifest + protocol tests + merge-gates + diff PR comment', acceptance:'CREATE-no-MERGE PR fails; MERGE PR passes with clean diff comment', deps:['wi-gs-02','wi-gs-04']},
  {id:'wi-gs-06', track:'track-G', type:'impl', title:'maverick local snapshot {create,list,delete,from-tag} + checkout via multi-DB', acceptance:'checkout <2s; counts match per snapshot', deps:['wi-lf-02']},
  {id:'wi-gs-07', track:'track-G', type:'graph-write', title:'Drift healing: graph-manifest-reapply Protocol (60s) + :Invariant + :DriftEvent', acceptance:'manual drift → detected in 60s → corrected on next cycle', deps:['wi-gs-02']},
  {id:'wi-gs-08', track:'track-G', type:'infra', title:'Admin-footgun closed: separate admin user, team user true RO on dev/prod', acceptance:'team user direct-write rejected; admin succeeds via systemd env-file', deps:['wi-gs-07']},
<<<<<<< HEAD
  {id:'wi-gs-09', track:'track-G', type:'docs', title:'docs/operations/graph-sync-ux.md + AGENTS.md update + reflect in :ContributorGuide', acceptance:'fresh contributor walks install→merged-PR using only these docs', deps:['wi-gs-03','wi-gs-04','wi-gs-06','wi-rb-07']}
=======
  {id:'wi-gs-09', track:'track-G', type:'docs', title:'docs/operations/graph-sync-ux.md + AGENTS.md update + reflect in :ContributorGuide', acceptance:'fresh contributor walks install→merged-PR using only these docs', deps:['wi-gs-03','wi-gs-04','wi-gs-06','wi-rb-07']},
  // Track H — Teammate Claude Code integration
  {id:'wi-tc-01', track:'track-H', type:'tooling', title:'~/.claude/CLAUDE.md rich directives block (triggers + cues + portal + hard rules, marker-delimited)', acceptance:'block appended idempotently; teammates Claude Code reaches for maverick CLI on matching triggers without being prompted; uninstall removes block intact', deps:['wi-rb-09']},
  {id:'wi-tc-03', track:'track-H', type:'tooling', title:'/maverick skill = full CLI pass-through (tokens after /maverick forward verbatim to the maverick binary)', acceptance:'/maverick <any cli tokens> forwards verbatim; /maverick alone prints help; no logic beyond pass-through', deps:['wi-rb-09']},
  {id:'wi-tc-05', track:'track-H', type:'tooling', title:'Read-only permissions allowlist in ~/.claude/settings.json (Bash(maverick ask:*), shell MATCH*/RETURN*, status/health/doctor) — mutating verbs still prompt', acceptance:'read-only invocations do not prompt; mutating verbs (fork/bootstrap/uninstall/shell CREATE) still prompt; uninstall removes exactly the managed entries', deps:['wi-rb-09']},
  {id:'wi-tc-06', track:'track-H', type:'tooling', title:'maverick uninstall reverses all Track H changes (CLAUDE.md block, skills/, allowlist entries)', acceptance:'after install → uninstall, zero Maverick string in ~/.claude/ and all non-maverick keys preserved; idempotent', deps:['wi-tc-01','wi-tc-03','wi-tc-05']},
  // Track I — Graph self-scaffolding (RepoFile + drift)
  {id:'wi-gs-11', track:'track-I', type:'schema', title:':RepoFile schema with constraints + :ENFORCES/:PROJECTED_FROM/:CONSUMED_BY relations', acceptance:'schema applied via autodeploy; constraint test: MERGE same path twice = one node', deps:['wi-gs-01','wi-gs-02']},
  {id:'wi-gs-12', track:'track-I', type:'graph-write', title:'graph/knowledge/repofiles.cypher seeded via scripts/build-repofiles-cypher.sh walker (git ls-files → MERGE statements)', acceptance:'every git-tracked file has a :RepoFile; walker re-runs produce identical output', deps:['wi-gs-11']},
  {id:'wi-gs-13', track:'track-I', type:'ci', title:'graph-repofile-drift CI job fails PR when tracked file missing :RepoFile or :RepoFile references missing file', acceptance:'add/remove a file without updating cypher → CI fails; regenerate via walker → CI passes', deps:['wi-gs-11','wi-gs-12','wi-gs-05']},
  {id:'wi-gs-14', track:'track-I', type:'impl', title:'Autodeploy extension: walker vs committed repofiles.cypher → :DriftEvent on mismatch (no auto-commit; fix is a human PR)', acceptance:'introduce a file without updating cypher → :DriftEvent emitted within 2min cycle', deps:['wi-gs-02','wi-gs-12']},
  {id:'wi-gs-15', track:'track-I', type:'pattern', title:'Amendment pattern: append-only tweaks to graph nodes via graph/amendments/*.cypher', acceptance:'graph/manifest.yaml includes amendments phase; graph/amendments/README.md documents rules (one tweak per file, never edited, supersede to correct); first live amendment lands (wi-lf-07 architect-migration); node.amendments array queryable; wi-cg-03 projection renders amendments inline', deps:[]}
>>>>>>> 789306e (plan: add wi-gs-15 (Amendment pattern) to Track I)
] AS w
MERGE (wi:WorkItem {node_id: w.id})
SET wi.title = w.title,
    wi.type = w.type,
    wi.acceptance = w.acceptance,
    wi.project = 'maverick',
    wi.plan = 'plan-v1.1-maverick',
    wi.status = coalesce(wi.status, 'pending')   // preserve status if WI already existed
WITH wi, w
MATCH (p:Plan {node_id:'plan-v1.1-maverick'})
MERGE (p)-[:HAS_WORKITEM]->(wi)
WITH wi, w
MATCH (tr:Track {node_id: w.track})
MERGE (tr)-[:HAS_WORKITEM]->(wi)
WITH wi, w
UNWIND (CASE WHEN w.deps = [] THEN [NULL] ELSE w.deps END) AS dep_id
  OPTIONAL MATCH (dep:WorkItem {node_id: dep_id})
  FOREACH (_ IN CASE WHEN dep IS NULL THEN [] ELSE [1] END |
    MERGE (wi)-[:DEPENDS_ON]->(dep)
  );

// ============================================================================
// :UXJourney nodes (three personas)
// ============================================================================
UNWIND [
  {id:'uxj-reader', persona:'reader', title:'Reader — query shared knowledge, never write', time_budget_min:5, depends_on:'Docker=no, Python=no, JDK=no, Neo4j=no', os_support:['win11','macos-arm64','macos-amd64','ubuntu']},
  {id:'uxj-contributor', persona:'contributor', title:'Contributor — write Cypher, land in maverick-dev', time_budget_min:10, depends_on:'Docker Desktop only (beyond Reader prereqs)', os_support:['win11-no-wsl','macos-arm64','macos-amd64','ubuntu']},
  {id:'uxj-maintainer', persona:'maintainer', title:'Maintainer — ops + releases', time_budget_min:0, depends_on:'SSH to pulse-server + all contributor deps', os_support:['ubuntu-pulse']}
] AS j
MERGE (uxj:UXJourney {node_id: j.id})
SET uxj.persona = j.persona,
    uxj.title = j.title,
    uxj.time_budget_min = j.time_budget_min,
    uxj.external_deps = j.depends_on,
    uxj.os_support = j.os_support,
    uxj.project = 'maverick',
    uxj.plan = 'plan-v1.1-maverick'
WITH uxj
MATCH (p:Plan {node_id:'plan-v1.1-maverick'})
MERGE (p)-[:HAS_JOURNEY]->(uxj);

// ============================================================================
// Session reflection (recorded for future session to pick up)
// ============================================================================
MERGE (r:SessionReflection {node_id: 'reflection-2026-04-20-v1.1-with-track-G'})
SET r.date = '2026-04-20',
    r.title = 'v1.1 plan committed with Track G (graph sync + repo-as-SoT)',
    r.narrative = 'Plan doc at docs/plan-v1.1-maverick.md. This file (graph/plans/plan-v1.1-maverick.cypher) is the source of truth for the Plan + 47 WorkItems. Track G is new: repo/graph as SoT, local-sync preserving work, PR-based graph changes, version switching, drift healing, admin-footgun closed. Direct admin writes to dev/prod are banned (wi-gs-08) — all future writes go through this file via autodeploy reapply (wi-gs-02). Next session: query MATCH (wi:WorkItem {plan:"plan-v1.1-maverick", status:"pending"}) WHERE NOT (wi)-[:DEPENDS_ON]->(:WorkItem {status:"pending"}) RETURN wi.node_id, wi.title. Fan out parallel Haiku agents per the feedback memory.',
    r.project = 'maverick',
    r.next_wi_suggestions = ['wi-ux-01','wi-rb-01','wi-qt-01','wi-cg-01','wi-gs-01'];

// ============================================================================
// Session mapping (2026-04-20 afternoon) — round-trip PR state into graph
// Principle: architect edits cypher → PR → autodeploy applies.
// Below reflects Wave 1-4 + Track H/I revision in progress.
// ============================================================================

UNWIND [
  {id:'wi-qt-01', status:'pr-open', pr:34},
  {id:'wi-ux-01', status:'pr-open', pr:37},
  {id:'wi-cg-01', status:'pr-open', pr:38},
  {id:'wi-rb-01', status:'pr-open', pr:39},
  {id:'wi-rb-03', status:'pr-open', pr:41},
  {id:'wi-ux-03', status:'pr-open', pr:42},
  {id:'wi-ux-04', status:'pr-open', pr:43},
  {id:'wi-ux-02', status:'pr-open', pr:44},
  {id:'wi-rb-02', status:'pr-open', pr:45},
  {id:'wi-ux-05', status:'pr-open', pr:46},
  {id:'wi-nt-01', status:'pr-open', pr:47},
  {id:'wi-rb-07', status:'pr-open', pr:48},
  {id:'wi-ux-08', status:'pr-open', pr:49},
  {id:'wi-rb-04', status:'pr-open', pr:50},
  {id:'wi-lf-01', status:'pr-open', pr:51},
  {id:'wi-gs-02', status:'pr-open', pr:52},
  {id:'wi-lf-02', status:'pr-open', pr:54},
  {id:'wi-lf-04', status:'pr-open', pr:55},
  {id:'wi-rb-06', status:'in-progress', pr:0},
  {id:'wi-cg-02', status:'in-progress', pr:0},
  {id:'wi-qt-04', status:'in-progress', pr:0},
  {id:'wi-ux-09', status:'in-progress', pr:0},
  {id:'wi-ux-10', status:'in-progress', pr:0}
] AS row
MATCH (wi:WorkItem {plan:'plan-v1.1-maverick', node_id: row.id})
SET wi.status = row.status,
    wi.pr_number = row.pr,
    wi.last_status_update_ts = datetime('2026-04-20T18:00:00Z');

// Session reflection update — 2026-04-20 afternoon
MERGE (r2:SessionReflection {node_id: 'reflection-2026-04-20-afternoon-waves-1-5'})
SET r2.date = '2026-04-20',
    r2.title = 'Waves 1-5 in flight; Track H revised to CLI-only; Track I added',
    r2.narrative = '18 PRs open (Waves 1-4 landed: #34/37/38/39/41/42/43/44/45/46/47/48/49/50/51/52/54/55). Wave 5 agents in flight: wi-rb-06, wi-cg-02, wi-qt-04, wi-ux-09, wi-ux-10. Locked design principles in plan doc: CLI-only interface, positive-reinforcement (no hooks, no MCP), no-direct-writes, read-only-default allowlist, architect-is-contributor, isolated-worktrees-for-parallel-agents, dogfood-what-you-build. File SoT model formalized: content-in-graph / projection-of-graph / meta-only. Track H rewritten to 4 CLI-only WIs (wi-tc-01/03/05/06). Track I added (wi-gs-11..14) for :RepoFile self-scaffolding + drift-check. Next: merge ready-green PRs, fire wi-cg-03 (export-guide) + wi-gs-01 (once rb-07 lands) + wi-rb-05/08 once rb-02 merges.',
    r2.project = 'maverick',
    r2.open_pr_count = 18,
    r2.in_flight_wi_count = 5;
