// @node_id: rule-novel-label-fixtures
// @label: "AgentInvocation"
// @kind: fixtures
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:45.296493
// Rule: rule-novel-label-fixtures
// ============================================================================
// @node_id: fixtures-agentinvocation-examples
// @label: "AgentInvocation sample fixtures"
// @kind: fixtures

