// @node_id: rule-novel-label-fixtures
// @label: "ApiEndpoint"
// @kind: fixtures
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:45.391285
// Rule: rule-novel-label-fixtures
// ============================================================================
// @node_id: fixtures-apiendpoint-examples
// @label: "ApiEndpoint sample fixtures"
// @kind: fixtures

MERGE (n:ApiEndpoint {node_id: 'endpoint-rpc-soft_delete_user_role'})
SET n += {content_hash: '46121a1b4e7fd244afbbe585d4840a08', created_at: 1776611658589, created_by: 'parse_api_endpoints', function_name: 'soft_delete_user_role', implementation_kind: 'postgrest-rpc', last_seen_at: 1776627115935, last_seen_sync: 'standalone-1db99e9b742c', method: 'POST', node_id: 'endpoint-rpc-soft_delete_user_role', path: '/rest/v1/rpc/soft_delete_user_role', project: 'maverick-dev-friend', returns: 'public.user_roles', security: 'INVOKER', signature: 'p_id               uuid,\n  p_expected_version integer', source: 'derived-rpc:soft_delete_user_role', subsystem: 'maverick-dev', volatility: 'VOLATILE'};

MERGE (n:ApiEndpoint {node_id: 'endpoint-hono-route-get-6666cd76'})
SET n += {content_hash: '21928e4f8afee5e0b924e3096b557508', created_at: 1776624427343, created_by: 'parse_api_endpoints', implementation_kind: 'hono-route', last_seen_at: 1776627115935, last_seen_sync: 'standalone-1db99e9b742c', method: 'GET', node_id: 'endpoint-hono-route-get-6666cd76', path: '/', project: 'maverick-dev-friend', source: 'derived-hono:/', subsystem: 'maverick-dev'};

MERGE (n:ApiEndpoint {node_id: 'endpoint-table-permission_state_rules'})
SET n += {allowed_methods: ['SELECT'], content_hash: '32643d1b2ab085c502b0ee9229cb9ee9', created_at: 1776611658589, created_by: 'parse_api_endpoints', implementation_kind: 'postgrest-table', last_seen_at: 1776627115935, last_seen_sync: 'standalone-1db99e9b742c', method: 'VARIES', node_id: 'endpoint-table-permission_state_rules', path: '/rest/v1/permission_state_rules', project: 'maverick-dev-friend', source: 'derived-table:permission_state_rules', subsystem: 'maverick-dev', table_name: 'permission_state_rules'};
