// @node_id: rule-novel-label-fixtures
// @label: "DriftReport"
// @kind: fixtures
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:45.409133
// Rule: rule-novel-label-fixtures
// ============================================================================
// @node_id: fixtures-driftreport-examples
// @label: "DriftReport sample fixtures"
// @kind: fixtures

MERGE (n:DriftReport {node_id: 'drift-1776621693330'})
SET n += {by_category: '{\'stale_principle_versions\': 0, \'fail_verdicts\': 4, \'warn_verdicts\': 27, \'undeclared_env_vars\': 12, \'tables_without_rls_but_with_triggers\': 0, \'definer_unpinned_search_path\': 0, \'fsd_inverted_imports\'…', created_at: 1776621693330, created_by: 'gen_drift_report', generated_at: 1776621693330, is_latest: false, node_id: 'drift-1776621693330', project: 'maverick-dev-friend', source: 'drift-sweep', subsystem: 'maverick-dev', total: 125};

MERGE (n:DriftReport {node_id: 'drift-1776612281006'})
SET n += {by_category: '{\'stale_principle_versions\': 0, \'fail_verdicts\': 4, \'warn_verdicts\': 25, \'undeclared_env_vars\': 12, \'tables_without_rls_but_with_triggers\': 0, \'definer_unpinned_search_path\': 0, \'fsd_inverted_imports\'…', created_at: 1776612281006, created_by: 'gen_drift_report', generated_at: 1776612281006, is_latest: false, node_id: 'drift-1776612281006', project: 'maverick-dev-friend', source: 'drift-sweep', subsystem: 'maverick-dev', total: 150};

MERGE (n:DriftReport {node_id: 'drift-1776615746247'})
SET n += {by_category: '{\'stale_principle_versions\': 0, \'fail_verdicts\': 4, \'warn_verdicts\': 25, \'undeclared_env_vars\': 12, \'tables_without_rls_but_with_triggers\': 0, \'definer_unpinned_search_path\': 0, \'fsd_inverted_imports\': 0, \'uncovered_frs\': 37', created_at: 1776615746247, created_by: 'gen_drift_report', generated_at: 1776615746247, is_latest: false, node_id: 'drift-1776615746247', project: 'maverick-dev-friend', source: 'drift-sweep', subsystem: 'maverick-dev', total: 93};
