// @node_id: rule-novel-label-fixtures
// @label: "FR"
// @kind: fixtures
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:45.366881
// Rule: rule-novel-label-fixtures
// ============================================================================
// @node_id: fixtures-fr-examples
// @label: "FR sample fixtures"
// @kind: fixtures

MERGE (n:FR {node_id: 'fr-auth-rbac-FR-053'})
SET n += {content_hash: 'b3e84181d7a1b93c6ff151791ab6b0b5', created_at: 1776611291885, created_by: 'parse_tasks', fr_id: 'FR-053', last_seen_at: 1776624424911, last_seen_sync: 'sync-08a0607db18e', node_id: 'fr-auth-rbac-FR-053', project: 'maverick-dev-friend', source: 'spec:auth-rbac#FR-053', spec_slug: 'auth-rbac', subsystem: 'maverick-dev'};

MERGE (n:FR {node_id: 'fr-auth-rbac-FR-027'})
SET n += {content_hash: 'c486a513a4018b181b3fc9555efd3f73', created_at: 1776611291885, created_by: 'parse_tasks', fr_id: 'FR-027', last_seen_at: 1776624424911, last_seen_sync: 'sync-08a0607db18e', node_id: 'fr-auth-rbac-FR-027', project: 'maverick-dev-friend', source: 'spec:auth-rbac#FR-027', spec_slug: 'auth-rbac', subsystem: 'maverick-dev'};

MERGE (n:FR {node_id: 'fr-auth-infra-hardening-FR-130'})
SET n += {content_hash: '33c3196358aaf4b488be3ab55fc8ea2d', created_at: 1776620545428, created_by: 'parse_tasks', fr_id: 'FR-130', last_seen_at: 1776624424911, last_seen_sync: 'sync-08a0607db18e', node_id: 'fr-auth-infra-hardening-FR-130', project: 'maverick-dev-friend', source: 'spec:auth-infra-hardening#FR-130', spec_slug: 'auth-infra-hardening', subsystem: 'maverick-dev'};
