// @node_id: rule-novel-label-fixtures
// @label: "Route"
// @kind: fixtures
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:45.432560
// Rule: rule-novel-label-fixtures
// ============================================================================
// @node_id: fixtures-route-examples
// @label: "Route sample fixtures"
// @kind: fixtures

MERGE (n:Route {node_id: 'route-get-f3f41ab8'})
SET n += {created_at: 1776627115063, created_by: 'parse_api_routes', extraction: 'regex-direct', framework: 'hono', handler_file: 'src/server/index.ts', method: 'GET', node_id: 'route-get-f3f41ab8', path: '/docs/openapi.json', project: 'maverick-dev-friend', source: 'route:GET:/docs/openapi.json', subsystem: 'maverick-dev'};

MERGE (n:Route {node_id: 'route-get-95fcbda6'})
SET n += {created_at: 1776627115063, created_by: 'parse_api_routes', extraction: 'regex-direct', framework: 'hono', handler_file: 'src/server/index.ts', method: 'GET', node_id: 'route-get-95fcbda6', path: '/api/health', project: 'maverick-dev-friend', source: 'route:GET:/api/health', subsystem: 'maverick-dev'};

MERGE (n:Route {node_id: 'route-post-1a92b9cb'})
SET n += {auth_required: true, created_at: 1776627115063, created_by: 'parse_api_routes', framework: 'hono', handler_file: 'src/server/routes/userinfo.ts', has_zod_input: true, method: 'POST', node_id: 'route-post-1a92b9cb', path: '/batch', project: 'maverick-dev-friend', source: 'route:POST:/batch', subsystem: 'maverick-dev'};
