// @node_id: rule-novel-label-fixtures
// @label: "SchemaVersion"
// @kind: fixtures
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:45.353131
// Rule: rule-novel-label-fixtures
// ============================================================================
// @node_id: fixtures-schemaversion-examples
// @label: "SchemaVersion sample fixtures"
// @kind: fixtures

MERGE (n:SchemaVersion {node_id: 'example-schemaversion-0'})
SET n += {created_at: 1776585483066, description: 'First formally canonicalized Maverick Dev graph shape. Includes amendments, principle versions, SQL-object parsing, ValidationRun version stamping, post-merge Graphiti episodes, and full infra-hardening batch (V0037–V0041).', dump_reference: 'backups/maverick-dev-20260419-123647.dump', is_current: true, migrations_through: 'V0041', name: 'v1.0.0', node_id: 'example-schemaversion-0', project: 'maverick-dev-friend', released_at: 1776585483066, released_by: 'V0042', released_on: '2026-04-19', subsystem: 'maverick-dev'};
