// @node_id: rule-novel-label-fixtures
// @label: "SpecArtifact"
// @kind: fixtures
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:45.421386
// Rule: rule-novel-label-fixtures
// ============================================================================
// @node_id: fixtures-specartifact-examples
// @label: "SpecArtifact sample fixtures"
// @kind: fixtures

MERGE (n:SpecArtifact {node_id: 'artifact-1421d6466346'})
SET n += {body: '---\nphase: P3\nwave: US3\nfeature: 003-auth-rbac\ndepends_on: [Phase 2E]\ntasks: [T091, T092, T093, T094]\nstatus: draft\nauthor: thesis\ndate: 2026-04-18\n---\n\n# P3-US3 Implementation Brief — Partner Removes Team Member Access Mid-Sessi', content_hash: 'd8bccc7ad858e17555230364885ea70e', created_at: 1776622539836, created_by: 'parse_spec_artifacts', declared_paths: [], kind: 'brief', last_seen_at: 1776628448739, last_seen_sync: 'standalone-c23be90825f2', lines: 254, name: 'P3-US3-brief.md', node_id: 'artifact-1421d6466346', path: 'specs/003-auth-rbac/briefs/P3-US3-brief.md', project: 'maverick-dev-friend', source: 'speckit:specs/003-auth-rbac/briefs/P3-US3-brief.md', spec_slug: 'auth-rbac', subsystem: 'maverick-dev'};

MERGE (n:SpecArtifact {node_id: 'artifact-fd83d5a0c4a9'})
SET n += {body: '---\ntask_id: T001-T010 (bundled)\nfeature: 003-auth-rbac\nphase: Phase 1 Setup (Shared Infrastructure)\nagents_required: [Ledger, Syndicate, Assay]\nconstitution_rules: [P-10, P-14, P-18, P-19, PLAN-07, PLAN-13, PLAN-17, PLAN-18, TASK-01, ', content_hash: 'b1789d39f7f886e7dba520ae3c3ba508', created_at: 1776622539836, created_by: 'parse_spec_artifacts', declared_paths: [], kind: 'brief', last_seen_at: 1776628448739, last_seen_sync: 'standalone-c23be90825f2', lines: 172, name: 'T001-T010-brief.md', node_id: 'artifact-fd83d5a0c4a9', path: 'specs/003-auth-rbac/briefs/T001-T010-brief.md', project: 'maverick-dev-friend', source: 'speckit:specs/003-auth-rbac/briefs/T001-T010-brief.md', spec_slug: 'auth-rbac', subsystem: 'maverick-dev'};

MERGE (n:SpecArtifact {node_id: 'artifact-b514f9cd356a'})
SET n += {body: '---\ntask_id: 2E (T041-T060 + T111b + T065 + FR-067 runbook)\nfeature: 003-auth-rbac\nagents: [Syndicate, Mint, Wire, Crank, Covenant, Assay, Minutes, Ledger]\nmandatory_skills:\n  T041: hono-app-scaffold\n  T042: hono-otel-middleware\n  T0', content_hash: 'd7302f8c9417d9ddd3440887f5309a98', created_at: 1776622539836, created_by: 'parse_spec_artifacts', declared_paths: [], kind: 'brief', last_seen_at: 1776628448739, last_seen_sync: 'standalone-c23be90825f2', lines: 473, name: '2E-brief.md', node_id: 'artifact-b514f9cd356a', path: 'specs/003-auth-rbac/briefs/2E-brief.md', project: 'maverick-dev-friend', source: 'speckit:specs/003-auth-rbac/briefs/2E-brief.md', spec_slug: 'auth-rbac', subsystem: 'maverick-dev'};
