// @node_id: rule-novel-label-fixtures
// @label: "SqlFunction"
// @kind: fixtures
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:45.308358
// Rule: rule-novel-label-fixtures
// ============================================================================
// @node_id: fixtures-sqlfunction-examples
// @label: "SqlFunction sample fixtures"
// @kind: fixtures

MERGE (n:SqlFunction {node_id: 'sqlfn-b691a1c3223b'})
SET n += {body: '\nDECLARE\n  v_row             public.user_roles;\n  v_current_version integer;\nBEGIN\n  UPDATE public.user_roles\n     SET deleted_at = now(),\n         is_active  = FALSE\n   WHERE id = p_id\n     AND version = p_expected_version\n     A', content_hash: 'c15c9f59e466ef6b09e80aa5658a02fa', created_at: 1776584017465, created_by: 'parse_sql_functions', file_path: 'drizzle/migrations/0013_soft_delete_user_role_rpc.sql', kind: 'FUNCTION', language: 'plpgsql', last_seen_at: 1776624415873, last_seen_sync: 'sync-08a0607db18e', line: 4, name: 'soft_delete_user_role', node_id: 'sqlfn-b691a1c3223b', project: 'maverick-dev-friend', returns: 'public.user_roles', schema: 'public', search_path: 'pg_catalog, public', security: 'INVOKER', signature: 'p_id               uuid,\n  p_expected_version integer', source: 'sql:drizzle/migrations/0013_soft_delete_user_role_rpc.sql#soft_delete_user_role', subsystem: 'maverick-dev', volatility: 'VOLATILE'};

MERGE (n:SqlFunction {node_id: 'sqlfn-7f0460b13305'})
SET n += {body: '\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1\n      FROM public.permission_state_rules\n     WHERE role_id       = NEW.role_id\n       AND permission_id = NEW.permission_id\n       AND state         = \'configurable\'\n  ) THEN\n    RAISE EXCEP', content_hash: '264b1e1195915f6b6cf8ebf685bd60d0', created_at: 1776615545828, created_by: 'parse_sql_functions', file_path: 'drizzle/migrations/0020_fpo_trigger_validation.sql', kind: 'FUNCTION', language: 'plpgsql', last_seen_at: 1776624415873, last_seen_sync: 'sync-08a0607db18e', line: 43, name: 'fpo_check_configurable_trg', node_id: 'sqlfn-7f0460b13305', project: 'maverick-dev-friend', returns: 'trigger', schema: 'public', search_path: 'pg_catalog, public', security: 'INVOKER', signature: '', source: 'sql:drizzle/migrations/0020_fpo_trigger_validation.sql#fpo_check_configurable_trg', subsystem: 'maverick-dev', volatility: 'STABLE'};

MERGE (n:SqlFunction {node_id: 'sqlfn-9092760c75b9'})
SET n += {body: '\n  SELECT count(*)::bigint\n  FROM public.audit_logs\n  WHERE actor_sub = \'system:unknown\'\n    AND occurred_at >= p_since\n    AND occurred_at <  now();\n', content_hash: '1b86c4dfde4fbefc0d2749fe1f3faefc', created_at: 1776584017465, created_by: 'parse_sql_functions', file_path: 'drizzle/migrations/0006a_unattributed_audit_helpers.sql', kind: 'FUNCTION', language: 'sql', last_seen_at: 1776624415873, last_seen_sync: 'sync-08a0607db18e', line: 33, name: 'count_unattributed_audit_rows', node_id: 'sqlfn-9092760c75b9', project: 'maverick-dev-friend', returns: 'bigint', schema: 'public', search_path: 'pg_catalog, public', security: 'DEFINER', signature: 'p_since timestamptz', source: 'sql:drizzle/migrations/0006a_unattributed_audit_helpers.sql#count_unattributed_audit_rows', subsystem: 'maverick-dev', volatility: 'STABLE'};
