// @node_id: rule-novel-label-fixtures
// @label: "SqlPolicy"
// @kind: fixtures
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:45.331523
// Rule: rule-novel-label-fixtures
// ============================================================================
// @node_id: fixtures-sqlpolicy-examples
// @label: "SqlPolicy sample fixtures"
// @kind: fixtures

MERGE (n:SqlPolicy {node_id: 'sqlpol-55692acd8006'})
SET n += {command: 'UPDATE', content_hash: 'e77ff2f9d378d08259066d7202019ca8', created_at: 1776584080127, created_by: 'parse_sql_functions', file_path: 'drizzle/migrations/0017_rls_per_operation_has_permission.sql', last_seen_at: 1776624415873, last_seen_sync: 'sync-08a0607db18e', line: 42, name: 'user_roles_fund_update', node_id: 'sqlpol-55692acd8006', permissive: 'PERMISSIVE', project: 'maverick-dev-friend', roles: ['m'], schema: 'public', source: 'sql:drizzle/migrations/0017_rls_per_operation_has_permission.sql#policy:user_roles_fund_update', subsystem: 'maverick-dev', table_name: 'user_roles'};

MERGE (n:SqlPolicy {node_id: 'sqlpol-39471c87056d'})
SET n += {command: 'SELECT', content_hash: '4c331956a05d24b8fe656c3db8a24d12', created_at: 1776584080127, created_by: 'parse_sql_functions', file_path: 'drizzle/migrations/0002a_rls_policies.sql', last_seen_at: 1776624415873, last_seen_sync: 'sync-08a0607db18e', line: 28, name: 'domain_events_fund_scope', node_id: 'sqlpol-39471c87056d', permissive: 'PERMISSIVE', project: 'maverick-dev-friend', roles: [''], schema: 'public', source: 'sql:drizzle/migrations/0002a_rls_policies.sql#policy:domain_events_fund_scope', subsystem: 'maverick-dev', table_name: 'domain_events'};

MERGE (n:SqlPolicy {node_id: 'sqlpol-3252a691d940'})
SET n += {command: 'ALL', content_hash: 'bc84b5925963e4e0519564f640250915', created_at: 1776584080127, created_by: 'parse_sql_functions', file_path: 'drizzle/migrations/0002a_rls_policies.sql', last_seen_at: 1776624415873, last_seen_sync: 'sync-08a0607db18e', line: 29, name: 'fund_permission_overrides_fund_scope', node_id: 'sqlpol-3252a691d940', permissive: 'PERMISSIVE', project: 'maverick-dev-friend', roles: [''], schema: 'public', source: 'sql:drizzle/migrations/0002a_rls_policies.sql#policy:fund_permission_overrides_fund_scope', subsystem: 'maverick-dev', table_name: 'fund_permission_overrides'};
