// @node_id: rule-novel-label-fixtures
// @label: "SqlTrigger"
// @kind: fixtures
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:45.319917
// Rule: rule-novel-label-fixtures
// ============================================================================
// @node_id: fixtures-sqltrigger-examples
// @label: "SqlTrigger sample fixtures"
// @kind: fixtures

MERGE (n:SqlTrigger {node_id: 'sqltrg-cd0c92fcafc5'})
SET n += {content_hash: '77e19e70fe448a348144b86fd2ab93be', created_at: 1776584017465, created_by: 'parse_sql_functions', event: 'INSERT OR DELETE', executes_fn: 'capture_audit', file_path: 'drizzle/migrations/0002_trigger_attachments.sql', last_seen_at: 1776624415873, last_seen_sync: 'sync-08a0607db18e', line: 531, name: 'audit_user_profiles_ins_del', node_id: 'sqltrg-cd0c92fcafc5', project: 'maverick-dev-friend', schema: 'public', source: 'sql:drizzle/migrations/0002_trigger_attachments.sql#trigger:audit_user_profiles_ins_del', subsystem: 'maverick-dev', table_name: 'user_profiles', timing: 'AFTER'};

MERGE (n:SqlTrigger {node_id: 'sqltrg-95c926d868b5'})
SET n += {content_hash: '0919b709799d02d16f68661259a6b945', created_at: 1776584017465, created_by: 'parse_sql_functions', event: 'UPDATE', executes_fn: 'bump_version', file_path: 'drizzle/migrations/0002_trigger_attachments.sql', last_seen_at: 1776624415873, last_seen_sync: 'sync-08a0607db18e', line: 431, name: 'bump_version_permission_state_rules', node_id: 'sqltrg-95c926d868b5', project: 'maverick-dev-friend', schema: 'public', source: 'sql:drizzle/migrations/0002_trigger_attachments.sql#trigger:bump_version_permission_state_rules', subsystem: 'maverick-dev', table_name: 'permission_state_rules', timing: 'BEFORE'};

MERGE (n:SqlTrigger {node_id: 'sqltrg-95fb9bfe0311'})
SET n += {content_hash: '6e12103fd0ad721933b16dfffc9cce18', created_at: 1776584017465, created_by: 'parse_sql_functions', event: 'INSERT OR UPDATE OR DELETE', executes_fn: 'roles_emit_domain_event_trg', file_path: 'drizzle/migrations/0002_trigger_attachments.sql', last_seen_at: 1776624415873, last_seen_sync: 'sync-08a0607db18e', line: 614, name: 'emit_domain_event_roles', node_id: 'sqltrg-95fb9bfe0311', project: 'maverick-dev-friend', schema: 'public', source: 'sql:drizzle/migrations/0002_trigger_attachments.sql#trigger:emit_domain_event_roles', subsystem: 'maverick-dev', table_name: 'roles', timing: 'AFTER'};
