// @node_id: rule-novel-label-fixtures
// @label: "SqlView"
// @kind: fixtures
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:45.343273
// Rule: rule-novel-label-fixtures
// ============================================================================
// @node_id: fixtures-sqlview-examples
// @label: "SqlView sample fixtures"
// @kind: fixtures

MERGE (n:SqlView {node_id: 'sqlview-3c569e812daf'})
SET n += {body: 'SELECT\n  NULLIF(current_setting(\'app.current_fund_id\', true), \'\')::uuid AS fund_id,\n\n  r.id    AS role_id,\n  r.name  AS role_name,\n  p.id    AS permission_id,\n  p.key   AS permission_key,\n  psr.state …', content_hash: 'f1e817b9ea5ba136d4c7e19a4be7abeb', created_at: 1776584017465, created_by: 'parse_sql_functions', file_path: 'drizzle/migrations/0010_permission_matrix_view_security_invoker.sql', last_seen_at: 1776624415873, last_seen_sync: 'sync-08a0607db18e', line: 48, name: 'permission_matrix_view', node_id: 'sqlview-3c569e812daf', project: 'maverick-dev-friend', schema: 'public', security_mode: 'INVOKER', source: 'sql:drizzle/migrations/0010_permission_matrix_view_security_invoker.sql#view:permission_matrix_view', subsystem: 'maverick-dev'};
