// @node_id: rule-novel-label-fixtures
// @label: "Task"
// @kind: fixtures
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:45.378134
// Rule: rule-novel-label-fixtures
// ============================================================================
// @node_id: fixtures-task-examples
// @label: "Task sample fixtures"
// @kind: fixtures

MERGE (n:Task {node_id: 'task-auth-rbac-T060'})
SET n += {content_hash: 'a83a71dcc4aa7d170a8e1af2416ce97a', created_at: 1776611291885, created_by: 'parse_tasks', description: '[P] Create `tests/setup-postgrest.ts` — contract-tier globalSetup that also provides `POSTGREST_URL` (can extend testcontainers setup).', is_parallel: true, last_seen_at: 1776624424911, last_seen_sync: 'sync-08a0607db18e', node_id: 'task-auth-rbac-T060', project: 'maverick-dev-friend', serves_frs: [], source: 'tasks:auth-rbac#T060', spec_slug: 'auth-rbac', status: 'done', stories: [], subsystem: 'maverick-dev', task_id: 'T060', touches_files: ['tests/setup-postgrest.ts']};

MERGE (n:Task {node_id: 'task-frontend-auth-wire-T024'})
SET n += {content_hash: '5db179ada54fba7e2c39537551b42fe7', created_at: 1776620545428, created_by: 'parse_tasks', description: '[US1] Wire `/login` page\'s "Create account" link in `src/app/login/page.tsx` (from T017) to `keycloak.register({ redirectUri: \'<base>/api/auth/callback?next=/\' })` (FR-073).', is_parallel: false, last_seen_at: 1776624424911, last_seen_sync: 'sync-08a0607db18e', node_id: 'task-frontend-auth-wire-T024', project: 'maverick-dev-friend', serves_frs: ['FR-073'], source: 'tasks:frontend-auth-wire#T024', spec_slug: 'frontend-auth-wire', status: 'todo', stories: ['US1'], subsystem: 'maverick-dev', task_id: 'T024', touches_files: ['src/app/login/page.tsx']};

MERGE (n:Task {node_id: 'task-auth-rbac-T025'})
SET n += {content_hash: '6493a65295e0bd5b81bf017cfc159868', created_at: 1776611291885, created_by: 'parse_tasks', description: '[P] Author `src/server/db/functions/capture_audit.sql` per `postgres-audit-trigger-jsonb`. VOLATILE, SECURITY DEFINER, search_path protected per FR-056.', is_parallel: true, last_seen_at: 1776624424911, last_seen_sync: 'sync-08a0607db18e', node_id: 'task-auth-rbac-T025', project: 'maverick-dev-friend', serves_frs: ['FR-056'], source: 'tasks:auth-rbac#T025', spec_slug: 'auth-rbac', status: 'done', stories: [], subsystem: 'maverick-dev', task_id: 'T025', touches_files: ['src/server/db/functions/capture_audit.sql']};
