// @node_id: protocol-export-graph-state
// @label: "Export Graph State"
// ============================================================================
// Protocol: Export Graph State
// ============================================================================
// Emits deterministic Cypher MERGE statements for the current domain graph.
// Each RETURN row is one line of the output .cypher file.
//
// This protocol runs inside cypher-shell --format plain. The wrapping runner
// (graph/runner/export-graph-state.sh) strips the formatting artifacts (column
// headers, surrounding quotes, escaped quotes) to produce clean text.
//
// Output structure:
//   Section 1: header comment lines
//   Section 2: node MERGEs, sorted by label then node_id
//   Section 3: edge MATCH-MERGEs with label-scoped matches, sorted for
//              deterministic output
//
// Replaces the legacy scripts/graph-export-state.py (FalkorDB-targeted) which
// had two bugs both fixed here by construction:
//   1. MerkleNode/MerkleTree were not excluded. Fixed: WHERE filters exclude
//      them explicitly. The clean graph should never contain Merkle entities
//      anyway (see graph/protocols/merkle-properties.cypher).
//   2. Edge emission used unscoped MATCH, producing Cartesian-product phantom
//      edges when the same node_id existed under different labels. Fixed: the
//      MATCH clauses below include labels(a)[0] and labels(b)[0] explicitly.
//
// Excluded from export:
//   - n.node_id IS NULL          (MERGE requires a stable identity key)
//   - QueryTrace                 (ephemeral telemetry, high volume)
//   - MerkleNode, MerkleTree     (legacy integrity entities — replaced by
//                                 per-node leaf_hash + Being.root_hash)
// ============================================================================


// --- Header ------------------------------------------------------------------
// cypher-shell --format plain does not preserve embedded newlines in a single
// string cell, so the header is emitted as several one-row RETURNs.

RETURN '// Graph state export — ' + toString(datetime()) AS line;
RETURN '// Deterministic: sorted by (label, node_id), edges by (src_label, src_id, type, dst_label, dst_id)' AS line;
RETURN '// Generated by graph/protocols/export-graph-state.cypher via graph/runner/export-graph-state.sh' AS line;
RETURN '// DO NOT HAND-EDIT. Re-export with: graph/runner/export-graph-state.sh' AS line;
RETURN '' AS line;
RETURN '// === NODES ===' AS line;


// --- Nodes -------------------------------------------------------------------
// Serialize each property as `k: apoc.convert.toJson(v)`. The JSON representation
// is valid Cypher literal syntax for strings, numbers, booleans, and lists.

// Exclude properties that are derived outputs (embeddings, merkle, phase1
// state, liveness, lifecycle). These are all listed as SkipKey nodes in the
// graph, so we load that list dynamically — one source of truth for what
// the exporter should skip AND what merkle should skip.
MATCH (sk:SkipKey)
WITH collect(sk.key) + ['node_id'] AS export_skip
MATCH (n)
WHERE n.node_id IS NOT NULL
  AND NOT n:QueryTrace
  AND NOT n:MerkleNode
  AND NOT n:MerkleTree
WITH n, export_skip, labels(n)[0] AS label
ORDER BY label, n.node_id
WITH label, n, export_skip,
     apoc.text.join(
       [k IN apoc.coll.sort(keys(n)) WHERE NOT k IN export_skip
        | 'n.' + k + ' = ' + apoc.convert.toJson(n[k])],
       ', '
     ) AS set_clause
RETURN 'MERGE (n:' + label + ' {node_id: ' + apoc.convert.toJson(n.node_id) + '}) SET ' + set_clause + ';' AS line;


// --- Edge section marker -----------------------------------------------------

RETURN '' AS line;
RETURN '// === EDGES ===' AS line;


// --- Edges (label-scoped MATCH — fixes the Cartesian-product phantom bug) ----

MATCH (a)-[r]->(b)
WHERE a.node_id IS NOT NULL
  AND b.node_id IS NOT NULL
  AND NOT a:QueryTrace AND NOT b:QueryTrace
  AND NOT a:MerkleNode AND NOT b:MerkleNode
  AND NOT a:MerkleTree AND NOT b:MerkleTree
WITH a, r, b,
     labels(a)[0] AS src_label,
     labels(b)[0] AS dst_label,
     type(r) AS edge_type
ORDER BY src_label, a.node_id, edge_type, dst_label, b.node_id
WITH src_label, a.node_id AS src_id, edge_type, dst_label, b.node_id AS dst_id, r,
     CASE size(keys(r))
       WHEN 0 THEN ''
       ELSE ' SET ' + apoc.text.join(
         [k IN apoc.coll.sort(keys(r)) | 'r.' + k + ' = ' + apoc.convert.toJson(r[k])],
         ', '
       )
     END AS edge_set
RETURN 'MATCH (a:' + src_label + ' {node_id: ' + apoc.convert.toJson(src_id) + '}), ' +
       '(b:' + dst_label + ' {node_id: ' + apoc.convert.toJson(dst_id) + '}) ' +
       'MERGE (a)-[r:' + edge_type + ']->(b)' + edge_set + ';' AS line;
