// @node_id: rule-novel-label-schema
// @label: "AgentInvocation"
// @kind: label-schema
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:45.794830
// Rule: rule-novel-label-schema
// ============================================================================
// @node_id: schema-agentinvocation-v1
// @label: "AgentInvocation schema v1 (auto-extracted)"
// @kind: knowledge

MERGE (s:SchemaDeclaration {node_id: 'schema-agentinvocation-v1'})
SET s.project = 'mycelium',
    s.for_label = 'AgentInvocation',
    s.observed_count = 0,
    s.properties = [],
    s.declared_at = datetime(),
    s.source = 'rule-novel-label-schema';

MERGE (inv:Invariant {node_id: 'invariant-agentinvocation-scoped'})
SET inv.project = 'mycelium',
    inv.label = 'Every :AgentInvocation has project scope',
    inv.severity = 'critical',
    inv.check_cypher = 'MATCH (n:AgentInvocation) WHERE n.project IS NULL RETURN count(n) AS violations',
    inv.heal_protocol = 'protocol-backfill-agentinvocation-project-scope';
