// @node_id: rule-novel-label-schema
// @label: "ApiEndpoint"
// @kind: label-schema
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:45.915868
// Rule: rule-novel-label-schema
// ============================================================================
// @node_id: schema-apiendpoint-v1
// @label: "ApiEndpoint schema v1 (auto-extracted)"
// @kind: knowledge

MERGE (s:SchemaDeclaration {node_id: 'schema-apiendpoint-v1'})
SET s.project = 'mycelium',
    s.for_label = 'ApiEndpoint',
    s.observed_count = 28,
    s.properties = ['path', 'source', 'created_by', 'function_name', 'node_id', 'volatility', 'created_at', 'content_hash', 'subsystem', 'last_seen_at', 'last_seen_sync', 'security', 'implementation_kind', 'method', 'signature', 'returns', 'project', 'table_name', 'allowed_methods', 'view_name'],
    s.declared_at = datetime(),
    s.source = 'rule-novel-label-schema';

MERGE (inv:Invariant {node_id: 'invariant-apiendpoint-scoped'})
SET inv.project = 'mycelium',
    inv.label = 'Every :ApiEndpoint has project scope',
    inv.severity = 'critical',
    inv.check_cypher = 'MATCH (n:ApiEndpoint) WHERE n.project IS NULL RETURN count(n) AS violations',
    inv.heal_protocol = 'protocol-backfill-apiendpoint-project-scope';
