// @node_id: decision-far-0003-auth-backend-scaffold-scope
// @label: "FAR-0003-auth-backend-scaffold-scope: FAR-0003-auth-backend-scaffold-scope: Backend Scaffold Lives Inside the Auth Spec"
// @kind: decision-instance
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:43.414591
// Rule: rule-novel-decision-instance
// ============================================================================
// @node_id: decision-decision-far-0003-auth-backend-scaffold-scope
// @label: "Decision: FAR-0003-auth-backend-scaffold-scope: FAR-0003-auth-backend-scaffold-scope: Backend Scaffold Lives Inside the Auth Spec"
// @kind: knowledge

MERGE (d:Decision {node_id: 'decision-far-0003-auth-backend-scaffold-scope'})
SET d.project = 'maverick-dev-friend',
    d.label = 'FAR-0003-auth-backend-scaffold-scope: FAR-0003-auth-backend-scaffold-scope: Backend Scaffold Lives Inside the Auth Spec',
    d.rationale = '- **Input:** Constitutional coverage on Day 1 → **Implication:** Only Option A satisfies every NON-NEGOTIABLE backend principle (P-02 api split via PostgREST, P-10 secrets via Infisical, P-11 integration auth via Nango, P-14 universal observability via OTel+Sentry, P-19 deployment portability via Docker Compose). Options B and C leave known violations until a follow-up spec ships, which accumulates risk on every subsequent feature.\n- **Input:** No prior backend spec exists (`spec_index.shipped_features: []`) → **Implication:** There is no pre-existing scaffold to depend on. Creating a placeholder `000-backend-scaffold` without going through `/speckit-specify` would just be deferring the work under a different filename; Option A faces the work directly.\n- **Input:** `.specify/catalog/infrastructure.json` lists every backend primitive with `provided_by_feature: 000-backend-scaffold` → **Implication:** To make the catalog honest, either we create `000-backend-scaffold` as a separate spec (adds one predecessor, splits the work) or we rewrite the catalog entries to `provided_by_feature: NNN-auth`. The chosen option does the latter via Area 0.5 catalog appends/edits.\n- **Input:** GATE-A (`/speckit-infra-readiness`) filters catalog entries by `applies_to.kind` against `project-shape.yml` → **Implication:** The scaffold work must include updating `project-shape.yml` to `kind: monorepo` (frontend + backend in one repo) as a Phase 0 deliverable, so GATE-A passes.\n- **Input:** The frontend RBAC model is already built and Storybook-green → **Implication:** Phase 1 of the auth spec wires the existing UI to the newly-scaffolded backend via a real `ServicesProvider` swap (mock → real). No frontend rewrite is part of this spec.\n\n---',
    d.status = 'Accepted',
    d.declared_at = datetime();
