// @node_id: decision-far-draft-runtime-smoke-gate
// @label: "FAR-DRAFT-runtime-smoke-gate: FAR: Runtime Smoke Gate — "Archive ≠ Ready""
// @kind: decision-instance
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:43.420366
// Rule: rule-novel-decision-instance
// ============================================================================
// @node_id: decision-decision-far-draft-runtime-smoke-gate
// @label: "Decision: FAR-DRAFT-runtime-smoke-gate: FAR: Runtime Smoke Gate — "Archive ≠ Ready""
// @kind: knowledge

MERGE (d:Decision {node_id: 'decision-far-draft-runtime-smoke-gate'})
SET d.project = 'maverick-dev-friend',
    d.label = 'FAR-DRAFT-runtime-smoke-gate: FAR: Runtime Smoke Gate — "Archive ≠ Ready"',
    d.rationale = '- The three bugs in 003 would have been caught at Step 2 — before ANY archive.\n- Harness tests validate application logic, not infrastructure deliverability. They\'re necessary but not sufficient.\n- "Deployable" is a first-class spec-kit concern per P-19 but had no enforcing gate.\n- Cost of smoke test per spec: ~10-60 min wall-clock. Cost of skipping: 3+ production bugs masked, hollow archive, lost team-lead credibility.',
    d.status = 'Draft',
    d.declared_at = datetime();
