// @node_id: amendment-c9f9cae3f8ed
// @label: "None"
// @kind: decision-instance
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:43.402881
// Rule: rule-novel-decision-instance
// ============================================================================
// @node_id: decision-amendment-c9f9cae3f8ed
// @label: "Decision: "
// @kind: knowledge

MERGE (d:Decision {node_id: 'amendment-c9f9cae3f8ed'})
SET d.project = 'maverick-dev-friend',
    d.label = '',
    d.rationale = '',
    d.status = 'active',
    d.declared_at = datetime();
