// @node_id: rule-novel-label-schema
// @label: "DriftReport"
// @kind: label-schema
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:45.930196
// Rule: rule-novel-label-schema
// ============================================================================
// @node_id: schema-driftreport-v1
// @label: "DriftReport schema v1 (auto-extracted)"
// @kind: knowledge

MERGE (s:SchemaDeclaration {node_id: 'schema-driftreport-v1'})
SET s.project = 'mycelium',
    s.for_label = 'DriftReport',
    s.observed_count = 7,
    s.properties = ['project', 'source', 'created_at', 'created_by', 'node_id', 'subsystem', 'by_category', 'total', 'is_latest', 'generated_at'],
    s.declared_at = datetime(),
    s.source = 'rule-novel-label-schema';

MERGE (inv:Invariant {node_id: 'invariant-driftreport-scoped'})
SET inv.project = 'mycelium',
    inv.label = 'Every :DriftReport has project scope',
    inv.severity = 'critical',
    inv.check_cypher = 'MATCH (n:DriftReport) WHERE n.project IS NULL RETURN count(n) AS violations',
    inv.heal_protocol = 'protocol-backfill-driftreport-project-scope';
