// @node_id: rule-novel-label-schema
// @label: "FR"
// @kind: label-schema
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:45.886752
// Rule: rule-novel-label-schema
// ============================================================================
// @node_id: schema-fr-v1
// @label: "FR schema v1 (auto-extracted)"
// @kind: knowledge

MERGE (s:SchemaDeclaration {node_id: 'schema-fr-v1'})
SET s.project = 'mycelium',
    s.for_label = 'FR',
    s.observed_count = 160,
    s.properties = ['fr_id', 'spec_slug', 'source', 'created_at', 'created_by', 'node_id', 'content_hash', 'subsystem', 'last_seen_at', 'last_seen_sync', 'project'],
    s.declared_at = datetime(),
    s.source = 'rule-novel-label-schema';

MERGE (inv:Invariant {node_id: 'invariant-fr-scoped'})
SET inv.project = 'mycelium',
    inv.label = 'Every :FR has project scope',
    inv.severity = 'critical',
    inv.check_cypher = 'MATCH (n:FR) WHERE n.project IS NULL RETURN count(n) AS violations',
    inv.heal_protocol = 'protocol-backfill-fr-project-scope';
