// @node_id: rule-novel-relationship-type
// @label: "ATTACHED_TO"
// @kind: rel-type
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:43.946194
// Rule: rule-novel-relationship-type
// ============================================================================
// @node_id: reltype-attached-to-v1
// @label: "ATTACHED_TO relationship type declaration"
// @kind: knowledge

MERGE (rt:RelationshipTypeDeclaration {node_id: 'reltype-attached-to-v1'})
SET rt.project = 'mycelium',
    rt.rel_type = 'ATTACHED_TO',
    rt.typical_shapes = ['Searchable-[ATTACHED_TO]->DbTable (30)'],
    rt.total_count = 30,
    rt.declared_at = datetime();
