// @node_id: rule-novel-relationship-type
// @label: "HAS_TASK"
// @kind: rel-type
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:43.994913
// Rule: rule-novel-relationship-type
// ============================================================================
// @node_id: reltype-has-task-v1
// @label: "HAS_TASK relationship type declaration"
// @kind: knowledge

MERGE (rt:RelationshipTypeDeclaration {node_id: 'reltype-has-task-v1'})
SET rt.project = 'mycelium',
    rt.rel_type = 'HAS_TASK',
    rt.typical_shapes = ['Entity-[HAS_TASK]->Searchable (289)'],
    rt.total_count = 289,
    rt.declared_at = datetime();
