// @node_id: rule-novel-relationship-type
// @label: "FIGHTS"
// @kind: rel-type
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:43.842643
// Rule: rule-novel-relationship-type
// ============================================================================
// @node_id: reltype-fights-v1
// @label: "FIGHTS relationship type declaration"
// @kind: knowledge

MERGE (rt:RelationshipTypeDeclaration {node_id: 'reltype-fights-v1'})
SET rt.project = 'mycelium',
    rt.rel_type = 'FIGHTS',
    rt.typical_shapes = ['None-[FIGHTS]->None (1)'],
    rt.total_count = 1,
    rt.declared_at = datetime();
