// @node_id: rule-novel-relationship-type
// @label: "VALIDATED_UNDER_AMENDMENT"
// @kind: rel-type
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:43.962672
// Rule: rule-novel-relationship-type
// ============================================================================
// @node_id: reltype-validated-under-amendment-v1
// @label: "VALIDATED_UNDER_AMENDMENT relationship type declaration"
// @kind: knowledge

MERGE (rt:RelationshipTypeDeclaration {node_id: 'reltype-validated-under-amendment-v1'})
SET rt.project = 'mycelium',
    rt.rel_type = 'VALIDATED_UNDER_AMENDMENT',
    rt.typical_shapes = ['Entity-[VALIDATED_UNDER_AMENDMENT]->Decision (4)'],
    rt.total_count = 4,
    rt.declared_at = datetime();
