// @node_id: rule-novel-relationship-type
// @label: "SERVES_FR"
// @kind: rel-type
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:44.027131
// Rule: rule-novel-relationship-type
// ============================================================================
// @node_id: reltype-serves-fr-v1
// @label: "SERVES_FR relationship type declaration"
// @kind: knowledge

MERGE (rt:RelationshipTypeDeclaration {node_id: 'reltype-serves-fr-v1'})
SET rt.project = 'mycelium',
    rt.rel_type = 'SERVES_FR',
    rt.typical_shapes = ['Searchable-[SERVES_FR]->Searchable (138)'],
    rt.total_count = 138,
    rt.declared_at = datetime();
