// @node_id: rule-novel-relationship-type
// @label: "IMPLEMENTED_BY"
// @kind: rel-type
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:44.042238
// Rule: rule-novel-relationship-type
// ============================================================================
// @node_id: reltype-implemented-by-v1
// @label: "IMPLEMENTED_BY relationship type declaration"
// @kind: knowledge

MERGE (rt:RelationshipTypeDeclaration {node_id: 'reltype-implemented-by-v1'})
SET rt.project = 'mycelium',
    rt.rel_type = 'IMPLEMENTED_BY',
    rt.typical_shapes = ['Searchable-[IMPLEMENTED_BY]->Searchable (15)', 'Searchable-[IMPLEMENTED_BY]->DbTable (10)', 'Searchable-[IMPLEMENTED_BY]->Route (5)'],
    rt.total_count = 30,
    rt.declared_at = datetime();
