// @node_id: rule-novel-relationship-type
// @label: "REFERENCES_TABLE"
// @kind: rel-type
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:43.894895
// Rule: rule-novel-relationship-type
// ============================================================================
// @node_id: reltype-references-table-v1
// @label: "REFERENCES_TABLE relationship type declaration"
// @kind: knowledge

MERGE (rt:RelationshipTypeDeclaration {node_id: 'reltype-references-table-v1'})
SET rt.project = 'mycelium',
    rt.rel_type = 'REFERENCES_TABLE',
    rt.typical_shapes = ['Searchable-[REFERENCES_TABLE]->DbTable (37)'],
    rt.total_count = 37,
    rt.declared_at = datetime();
