// @node_id: rule-novel-relationship-type
// @label: "TOUCHES"
// @kind: rel-type
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:44.011354
// Rule: rule-novel-relationship-type
// ============================================================================
// @node_id: reltype-touches-v1
// @label: "TOUCHES relationship type declaration"
// @kind: knowledge

MERGE (rt:RelationshipTypeDeclaration {node_id: 'reltype-touches-v1'})
SET rt.project = 'mycelium',
    rt.rel_type = 'TOUCHES',
    rt.typical_shapes = ['Searchable-[TOUCHES]->CodeFile (128)'],
    rt.total_count = 128,
    rt.declared_at = datetime();
