// @node_id: rule-novel-relationship-type
// @label: "CALLS_FUNCTION"
// @kind: rel-type
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:44.058146
// Rule: rule-novel-relationship-type
// ============================================================================
// @node_id: reltype-calls-function-v1
// @label: "CALLS_FUNCTION relationship type declaration"
// @kind: knowledge

MERGE (rt:RelationshipTypeDeclaration {node_id: 'reltype-calls-function-v1'})
SET rt.project = 'mycelium',
    rt.rel_type = 'CALLS_FUNCTION',
    rt.typical_shapes = ['Searchable-[CALLS_FUNCTION]->Searchable (14)'],
    rt.total_count = 14,
    rt.declared_at = datetime();
