// @node_id: rule-novel-relationship-type
// @label: "HAS_ARTIFACT"
// @kind: rel-type
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:44.088254
// Rule: rule-novel-relationship-type
// ============================================================================
// @node_id: reltype-has-artifact-v1
// @label: "HAS_ARTIFACT relationship type declaration"
// @kind: knowledge

MERGE (rt:RelationshipTypeDeclaration {node_id: 'reltype-has-artifact-v1'})
SET rt.project = 'mycelium',
    rt.rel_type = 'HAS_ARTIFACT',
    rt.typical_shapes = ['Entity-[HAS_ARTIFACT]->Searchable (53)'],
    rt.total_count = 53,
    rt.declared_at = datetime();
