// @node_id: rule-novel-relationship-type
// @label: "DEFINES_TABLE"
// @kind: rel-type
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:43.859695
// Rule: rule-novel-relationship-type
// ============================================================================
// @node_id: reltype-defines-table-v1
// @label: "DEFINES_TABLE relationship type declaration"
// @kind: knowledge

MERGE (rt:RelationshipTypeDeclaration {node_id: 'reltype-defines-table-v1'})
SET rt.project = 'mycelium',
    rt.rel_type = 'DEFINES_TABLE',
    rt.typical_shapes = ['CodeFile-[DEFINES_TABLE]->DbTable (10)'],
    rt.total_count = 10,
    rt.declared_at = datetime();
