// @node_id: rule-novel-relationship-type
// @label: "DEFINES_SQL_OBJECT"
// @kind: rel-type
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:43.877622
// Rule: rule-novel-relationship-type
// ============================================================================
// @node_id: reltype-defines-sql-object-v1
// @label: "DEFINES_SQL_OBJECT relationship type declaration"
// @kind: knowledge

MERGE (rt:RelationshipTypeDeclaration {node_id: 'reltype-defines-sql-object-v1'})
SET rt.project = 'mycelium',
    rt.rel_type = 'DEFINES_SQL_OBJECT',
    rt.typical_shapes = ['CodeFile-[DEFINES_SQL_OBJECT]->Searchable (102)'],
    rt.total_count = 102,
    rt.declared_at = datetime();
