// @node_id: rule-novel-relationship-type
// @label: "DECLARES_ENDPOINT"
// @kind: rel-type
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:44.118928
// Rule: rule-novel-relationship-type
// ============================================================================
// @node_id: reltype-declares-endpoint-v1
// @label: "DECLARES_ENDPOINT relationship type declaration"
// @kind: knowledge

MERGE (rt:RelationshipTypeDeclaration {node_id: 'reltype-declares-endpoint-v1'})
SET rt.project = 'mycelium',
    rt.rel_type = 'DECLARES_ENDPOINT',
    rt.typical_shapes = ['Searchable-[DECLARES_ENDPOINT]->Searchable (15)'],
    rt.total_count = 15,
    rt.declared_at = datetime();
