// @node_id: rule-novel-relationship-type
// @label: "WRITES"
// @kind: rel-type
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:44.073409
// Rule: rule-novel-relationship-type
// ============================================================================
// @node_id: reltype-writes-v1
// @label: "WRITES relationship type declaration"
// @kind: knowledge

MERGE (rt:RelationshipTypeDeclaration {node_id: 'reltype-writes-v1'})
SET rt.project = 'mycelium',
    rt.rel_type = 'WRITES',
    rt.typical_shapes = ['Searchable-[WRITES]->DbTable (14)'],
    rt.total_count = 14,
    rt.declared_at = datetime();
