// @node_id: rule-novel-relationship-type
// @label: "APPLIES_TO"
// @kind: rel-type
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:43.929271
// Rule: rule-novel-relationship-type
// ============================================================================
// @node_id: reltype-applies-to-v1
// @label: "APPLIES_TO relationship type declaration"
// @kind: knowledge

MERGE (rt:RelationshipTypeDeclaration {node_id: 'reltype-applies-to-v1'})
SET rt.project = 'mycelium',
    rt.rel_type = 'APPLIES_TO',
    rt.typical_shapes = ['Searchable-[APPLIES_TO]->DbTable (19)'],
    rt.total_count = 19,
    rt.declared_at = datetime();
