// @node_id: rule-novel-relationship-type
// @label: "HANDLES_ROUTE"
// @kind: rel-type
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:44.103655
// Rule: rule-novel-relationship-type
// ============================================================================
// @node_id: reltype-handles-route-v1
// @label: "HANDLES_ROUTE relationship type declaration"
// @kind: knowledge

MERGE (rt:RelationshipTypeDeclaration {node_id: 'reltype-handles-route-v1'})
SET rt.project = 'mycelium',
    rt.rel_type = 'HANDLES_ROUTE',
    rt.typical_shapes = ['CodeFile-[HANDLES_ROUTE]->Route (6)'],
    rt.total_count = 6,
    rt.declared_at = datetime();
