// @node_id: rule-novel-relationship-type
// @label: "HAS_FR"
// @kind: rel-type
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:43.978904
// Rule: rule-novel-relationship-type
// ============================================================================
// @node_id: reltype-has-fr-v1
// @label: "HAS_FR relationship type declaration"
// @kind: knowledge

MERGE (rt:RelationshipTypeDeclaration {node_id: 'reltype-has-fr-v1'})
SET rt.project = 'mycelium',
    rt.rel_type = 'HAS_FR',
    rt.typical_shapes = ['Entity-[HAS_FR]->Searchable (160)'],
    rt.total_count = 160,
    rt.declared_at = datetime();
