// @node_id: rule-novel-relationship-type
// @label: "EXECUTES_FUNCTION"
// @kind: rel-type
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:43.912802
// Rule: rule-novel-relationship-type
// ============================================================================
// @node_id: reltype-executes-function-v1
// @label: "EXECUTES_FUNCTION relationship type declaration"
// @kind: knowledge

MERGE (rt:RelationshipTypeDeclaration {node_id: 'reltype-executes-function-v1'})
SET rt.project = 'mycelium',
    rt.rel_type = 'EXECUTES_FUNCTION',
    rt.typical_shapes = ['Searchable-[EXECUTES_FUNCTION]->Searchable (30)'],
    rt.total_count = 30,
    rt.declared_at = datetime();
