// @node_id: rule-novel-label-schema
// @label: "Route"
// @kind: label-schema
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:45.957534
// Rule: rule-novel-label-schema
// ============================================================================
// @node_id: schema-route-v1
// @label: "Route schema v1 (auto-extracted)"
// @kind: knowledge

MERGE (s:SchemaDeclaration {node_id: 'schema-route-v1'})
SET s.project = 'mycelium',
    s.for_label = 'Route',
    s.observed_count = 5,
    s.properties = ['source', 'created_by', 'extraction', 'created_at', 'node_id', 'handler_file', 'path', 'method', 'framework', 'subsystem', 'project', 'has_zod_input', 'auth_required'],
    s.declared_at = datetime(),
    s.source = 'rule-novel-label-schema';

MERGE (inv:Invariant {node_id: 'invariant-route-scoped'})
SET inv.project = 'mycelium',
    inv.label = 'Every :Route has project scope',
    inv.severity = 'critical',
    inv.check_cypher = 'MATCH (n:Route) WHERE n.project IS NULL RETURN count(n) AS violations',
    inv.heal_protocol = 'protocol-backfill-route-project-scope';
