// @node_id: rule-novel-label-schema
// @label: "SchemaVersion"
// @kind: label-schema
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:45.871355
// Rule: rule-novel-label-schema
// ============================================================================
// @node_id: schema-schemaversion-v1
// @label: "SchemaVersion schema v1 (auto-extracted)"
// @kind: knowledge

MERGE (s:SchemaDeclaration {node_id: 'schema-schemaversion-v1'})
SET s.project = 'mycelium',
    s.for_label = 'SchemaVersion',
    s.observed_count = 1,
    s.properties = ['released_by', 'migrations_through', 'dump_reference', 'released_at', 'released_on', 'name', 'is_current', 'description', 'subsystem', 'created_at'],
    s.declared_at = datetime(),
    s.source = 'rule-novel-label-schema';

MERGE (inv:Invariant {node_id: 'invariant-schemaversion-scoped'})
SET inv.project = 'mycelium',
    inv.label = 'Every :SchemaVersion has project scope',
    inv.severity = 'critical',
    inv.check_cypher = 'MATCH (n:SchemaVersion) WHERE n.project IS NULL RETURN count(n) AS violations',
    inv.heal_protocol = 'protocol-backfill-schemaversion-project-scope';
