// @node_id: rule-novel-label-schema
// @label: "SpecArtifact"
// @kind: label-schema
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:45.943481
// Rule: rule-novel-label-schema
// ============================================================================
// @node_id: schema-specartifact-v1
// @label: "SpecArtifact schema v1 (auto-extracted)"
// @kind: knowledge

MERGE (s:SchemaDeclaration {node_id: 'schema-specartifact-v1'})
SET s.project = 'mycelium',
    s.for_label = 'SpecArtifact',
    s.observed_count = 53,
    s.properties = ['content_hash', 'kind', 'spec_slug', 'created_by', 'name', 'declared_paths', 'node_id', 'path', 'source', 'last_seen_sync', 'subsystem', 'created_at', 'lines', 'body', 'last_seen_at', 'project'],
    s.declared_at = datetime(),
    s.source = 'rule-novel-label-schema';

MERGE (inv:Invariant {node_id: 'invariant-specartifact-scoped'})
SET inv.project = 'mycelium',
    inv.label = 'Every :SpecArtifact has project scope',
    inv.severity = 'critical',
    inv.check_cypher = 'MATCH (n:SpecArtifact) WHERE n.project IS NULL RETURN count(n) AS violations',
    inv.heal_protocol = 'protocol-backfill-specartifact-project-scope';
