// @node_id: rule-novel-label-schema
// @label: "SqlFunction"
// @kind: label-schema
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:45.812875
// Rule: rule-novel-label-schema
// ============================================================================
// @node_id: schema-sqlfunction-v1
// @label: "SqlFunction schema v1 (auto-extracted)"
// @kind: knowledge

MERGE (s:SchemaDeclaration {node_id: 'schema-sqlfunction-v1'})
SET s.project = 'mycelium',
    s.for_label = 'SqlFunction',
    s.observed_count = 26,
    s.properties = ['search_path', 'volatility', 'returns', 'kind', 'security', 'content_hash', 'subsystem', 'last_seen_at', 'last_seen_sync', 'schema', 'language', 'created_by', 'created_at', 'name', 'node_id', 'source', 'body', 'signature', 'file_path', 'line', 'project'],
    s.declared_at = datetime(),
    s.source = 'rule-novel-label-schema';

MERGE (inv:Invariant {node_id: 'invariant-sqlfunction-scoped'})
SET inv.project = 'mycelium',
    inv.label = 'Every :SqlFunction has project scope',
    inv.severity = 'critical',
    inv.check_cypher = 'MATCH (n:SqlFunction) WHERE n.project IS NULL RETURN count(n) AS violations',
    inv.heal_protocol = 'protocol-backfill-sqlfunction-project-scope';
