// @node_id: rule-novel-label-schema
// @label: "SqlPolicy"
// @kind: label-schema
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:45.843111
// Rule: rule-novel-label-schema
// ============================================================================
// @node_id: schema-sqlpolicy-v1
// @label: "SqlPolicy schema v1 (auto-extracted)"
// @kind: knowledge

MERGE (s:SchemaDeclaration {node_id: 'schema-sqlpolicy-v1'})
SET s.project = 'mycelium',
    s.for_label = 'SqlPolicy',
    s.observed_count = 19,
    s.properties = ['created_by', 'name', 'created_at', 'table_name', 'node_id', 'roles', 'content_hash', 'subsystem', 'permissive', 'source', 'last_seen_sync', 'schema', 'last_seen_at', 'command', 'file_path', 'line', 'project'],
    s.declared_at = datetime(),
    s.source = 'rule-novel-label-schema';

MERGE (inv:Invariant {node_id: 'invariant-sqlpolicy-scoped'})
SET inv.project = 'mycelium',
    inv.label = 'Every :SqlPolicy has project scope',
    inv.severity = 'critical',
    inv.check_cypher = 'MATCH (n:SqlPolicy) WHERE n.project IS NULL RETURN count(n) AS violations',
    inv.heal_protocol = 'protocol-backfill-sqlpolicy-project-scope';
