// @node_id: rule-novel-label-schema
// @label: "SqlTrigger"
// @kind: label-schema
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:45.827763
// Rule: rule-novel-label-schema
// ============================================================================
// @node_id: schema-sqltrigger-v1
// @label: "SqlTrigger schema v1 (auto-extracted)"
// @kind: knowledge

MERGE (s:SchemaDeclaration {node_id: 'schema-sqltrigger-v1'})
SET s.project = 'mycelium',
    s.for_label = 'SqlTrigger',
    s.observed_count = 30,
    s.properties = ['created_by', 'executes_fn', 'event', 'name', 'node_id', 'table_name', 'content_hash', 'subsystem', 'created_at', 'source', 'last_seen_sync', 'timing', 'last_seen_at', 'file_path', 'schema', 'line', 'project'],
    s.declared_at = datetime(),
    s.source = 'rule-novel-label-schema';

MERGE (inv:Invariant {node_id: 'invariant-sqltrigger-scoped'})
SET inv.project = 'mycelium',
    inv.label = 'Every :SqlTrigger has project scope',
    inv.severity = 'critical',
    inv.check_cypher = 'MATCH (n:SqlTrigger) WHERE n.project IS NULL RETURN count(n) AS violations',
    inv.heal_protocol = 'protocol-backfill-sqltrigger-project-scope';
