// @node_id: rule-novel-label-schema
// @label: "SqlView"
// @kind: label-schema
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:45.856908
// Rule: rule-novel-label-schema
// ============================================================================
// @node_id: schema-sqlview-v1
// @label: "SqlView schema v1 (auto-extracted)"
// @kind: knowledge

MERGE (s:SchemaDeclaration {node_id: 'schema-sqlview-v1'})
SET s.project = 'mycelium',
    s.for_label = 'SqlView',
    s.observed_count = 1,
    s.properties = ['project', 'created_by', 'name', 'node_id', 'source', 'security_mode', 'created_at', 'content_hash', 'last_seen_at', 'subsystem', 'last_seen_sync', 'body', 'schema', 'file_path', 'line'],
    s.declared_at = datetime(),
    s.source = 'rule-novel-label-schema';

MERGE (inv:Invariant {node_id: 'invariant-sqlview-scoped'})
SET inv.project = 'mycelium',
    inv.label = 'Every :SqlView has project scope',
    inv.severity = 'critical',
    inv.check_cypher = 'MATCH (n:SqlView) WHERE n.project IS NULL RETURN count(n) AS violations',
    inv.heal_protocol = 'protocol-backfill-sqlview-project-scope';
