// @node_id: rule-novel-label-schema
// @label: "Task"
// @kind: label-schema
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:45.902246
// Rule: rule-novel-label-schema
// ============================================================================
// @node_id: schema-task-v1
// @label: "Task schema v1 (auto-extracted)"
// @kind: knowledge

MERGE (s:SchemaDeclaration {node_id: 'schema-task-v1'})
SET s.project = 'mycelium',
    s.for_label = 'Task',
    s.observed_count = 289,
    s.properties = ['spec_slug', 'task_id', 'source', 'created_at', 'created_by', 'node_id', 'description', 'content_hash', 'subsystem', 'last_seen_at', 'status', 'last_seen_sync', 'stories', 'is_parallel', 'serves_frs', 'touches_files', 'project'],
    s.declared_at = datetime(),
    s.source = 'rule-novel-label-schema';

MERGE (inv:Invariant {node_id: 'invariant-task-scoped'})
SET inv.project = 'mycelium',
    inv.label = 'Every :Task has project scope',
    inv.severity = 'critical',
    inv.check_cypher = 'MATCH (n:Task) WHERE n.project IS NULL RETURN count(n) AS violations',
    inv.heal_protocol = 'protocol-backfill-task-project-scope';
