// @node_id: tc-drift-total-bounded
// @label: "Latest :DriftReport.total < 200 (regression guard)"
// @kind: testcase-instance
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:44.878088
// Rule: rule-novel-testcase-instance
// ============================================================================
// @node_id: test-tc-drift-total-bounded
// @label: "Latest :DriftReport.total < 200 (regression guard)"
// @kind: knowledge

MERGE (tc:TestCase {node_id: 'tc-drift-total-bounded'})
SET tc.project = 'maverick-dev-friend',
    tc.label = 'Latest :DriftReport.total < 200 (regression guard)',
    tc.claim = '',
    tc.verify_cypher = '',
    tc.declared_at = datetime();
