// @node_id: tc-task-valid-status
// @label: "Every :Task.status ∈ {done, todo, absorbed, deferred}"
// @kind: testcase-instance
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:44.864798
// Rule: rule-novel-testcase-instance
// ============================================================================
// @node_id: test-tc-task-valid-status
// @label: "Every :Task.status ∈ {done, todo, absorbed, deferred}"
// @kind: knowledge

MERGE (tc:TestCase {node_id: 'tc-task-valid-status'})
SET tc.project = 'maverick-dev-friend',
    tc.label = 'Every :Task.status ∈ {done, todo, absorbed, deferred}',
    tc.claim = '',
    tc.verify_cypher = '',
    tc.declared_at = datetime();
