// @node_id: tc-fr-has-spec
// @label: "Every :FR is declared by a :Spec via HAS_FR"
// @kind: testcase-instance
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:44.858659
// Rule: rule-novel-testcase-instance
// ============================================================================
// @node_id: test-tc-fr-has-spec
// @label: "Every :FR is declared by a :Spec via HAS_FR"
// @kind: knowledge

MERGE (tc:TestCase {node_id: 'tc-fr-has-spec'})
SET tc.project = 'maverick-dev-friend',
    tc.label = 'Every :FR is declared by a :Spec via HAS_FR',
    tc.claim = '',
    tc.verify_cypher = '',
    tc.declared_at = datetime();
