// @node_id: tc-amendment-has-validation
// @label: "Every constitution amendment has at least one post-amendment ValidationRun"
// @kind: testcase-instance
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:44.887018
// Rule: rule-novel-testcase-instance
// ============================================================================
// @node_id: test-tc-amendment-has-validation
// @label: "Every constitution amendment has at least one post-amendment ValidationRun"
// @kind: knowledge

MERGE (tc:TestCase {node_id: 'tc-amendment-has-validation'})
SET tc.project = 'maverick-dev-friend',
    tc.label = 'Every constitution amendment has at least one post-amendment ValidationRun',
    tc.claim = '',
    tc.verify_cypher = '',
    tc.declared_at = datetime();
