// @node_id: tc-library-referenced
// @label: "Fewer than 50 :Library nodes with no incoming edges"
// @kind: testcase-instance
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:44.900175
// Rule: rule-novel-testcase-instance
// ============================================================================
// @node_id: test-tc-library-referenced
// @label: "Fewer than 50 :Library nodes with no incoming edges"
// @kind: knowledge

MERGE (tc:TestCase {node_id: 'tc-library-referenced'})
SET tc.project = 'maverick-dev-friend',
    tc.label = 'Fewer than 50 :Library nodes with no incoming edges',
    tc.claim = '',
    tc.verify_cypher = '',
    tc.declared_at = datetime();
