// @node_id: tc-write-endpoint-audited
// @label: "Every :ApiEndpoint that WRITES has an audit trigger on the target table"
// @kind: testcase-instance
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:44.895751
// Rule: rule-novel-testcase-instance
// ============================================================================
// @node_id: test-tc-write-endpoint-audited
// @label: "Every :ApiEndpoint that WRITES has an audit trigger on the target table"
// @kind: knowledge

MERGE (tc:TestCase {node_id: 'tc-write-endpoint-audited'})
SET tc.project = 'maverick-dev-friend',
    tc.label = 'Every :ApiEndpoint that WRITES has an audit trigger on the target table',
    tc.claim = '',
    tc.verify_cypher = '',
    tc.declared_at = datetime();
