// @node_id: tc-api-endpoint-impl
// @label: "Every :ApiEndpoint has an IMPLEMENTED_BY edge"
// @kind: testcase-instance
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:44.871824
// Rule: rule-novel-testcase-instance
// ============================================================================
// @node_id: test-tc-api-endpoint-impl
// @label: "Every :ApiEndpoint has an IMPLEMENTED_BY edge"
// @kind: knowledge

MERGE (tc:TestCase {node_id: 'tc-api-endpoint-impl'})
SET tc.project = 'maverick-dev-friend',
    tc.label = 'Every :ApiEndpoint has an IMPLEMENTED_BY edge',
    tc.claim = '',
    tc.verify_cypher = '',
    tc.declared_at = datetime();
