// @node_id: tc-undeclared-env-bounded
// @label: "Fewer than 10 env vars used in code but absent from .env.example"
// @kind: testcase-instance
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:44.890957
// Rule: rule-novel-testcase-instance
// ============================================================================
// @node_id: test-tc-undeclared-env-bounded
// @label: "Fewer than 10 env vars used in code but absent from .env.example"
// @kind: knowledge

MERGE (tc:TestCase {node_id: 'tc-undeclared-env-bounded'})
SET tc.project = 'maverick-dev-friend',
    tc.label = 'Fewer than 10 env vars used in code but absent from .env.example',
    tc.claim = '',
    tc.verify_cypher = '',
    tc.declared_at = datetime();
