// @node_id: tc-validation-is-latest-unique
// @label: "At most one :ValidationRun {is_latest: true} per (target_far, constraint_id, mode)"
// @kind: testcase-instance
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:44.882867
// Rule: rule-novel-testcase-instance
// ============================================================================
// @node_id: test-tc-validation-is-latest-unique
// @label: "At most one :ValidationRun {is_latest: true} per (target_far, constraint_id, mode)"
// @kind: knowledge

MERGE (tc:TestCase {node_id: 'tc-validation-is-latest-unique'})
SET tc.project = 'maverick-dev-friend',
    tc.label = 'At most one :ValidationRun {is_latest: true} per (target_far, constraint_id, mode)',
    tc.claim = '',
    tc.verify_cypher = '',
    tc.declared_at = datetime();
