// @node_id: tc-cherry-picked-branches-stale
// @label: "Branches with effective_merge_state=cherry-picked >7 days old"
// @kind: testcase-instance
//
// Auto-generated by scripts/contribute.py on 2026-04-20T10:30:44.903850
// Rule: rule-novel-testcase-instance
// ============================================================================
// @node_id: test-tc-cherry-picked-branches-stale
// @label: "Branches with effective_merge_state=cherry-picked >7 days old"
// @kind: knowledge

MERGE (tc:TestCase {node_id: 'tc-cherry-picked-branches-stale'})
SET tc.project = 'maverick-dev-friend',
    tc.label = 'Branches with effective_merge_state=cherry-picked >7 days old',
    tc.claim = '',
    tc.verify_cypher = '',
    tc.declared_at = datetime();
