#!/usr/bin/env python3
"""
vocabulary-backfill.py
======================
Load extracted vocabulary JSONL and backfill into Neo4j using cypher protocol.

Usage:
  python3 graph/runner/vocabulary-backfill.py [--corpus-file PATH] [--extract]

Defaults:
  corpus_file: /tmp/vocab-corpus.jsonl (generated by extract-vocabulary.py --corpus)
  extract: if set, run extract-vocabulary.py --corpus first

Process:
  1. Optionally run extract-vocabulary.py --corpus to generate JSONL
  2. Load JSONL records into memory
  3. Call vocabulary-backfill.cypher protocol with all records at once
  4. Report statistics before/after
"""
import argparse
import json
import os
import subprocess
import sys
import time


def load_records(filepath: str) -> list[dict]:
    """Load JSONL records from file."""
    records = []
    try:
        with open(filepath, 'r') as f:
            for line in f:
                line = line.strip()
                if line:
                    records.append(json.loads(line))
    except FileNotFoundError:
        print(f"ERROR: File not found: {filepath}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"ERROR: Invalid JSON in {filepath}: {e}", file=sys.stderr)
        sys.exit(1)
    return records


def run_cypher_with_params(cypher_text: str, params: dict) -> str:
    """Execute cypher via docker exec, passing params as JSON file."""
    # Write params to temp file
    import tempfile
    with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
        json.dump(params, f)
        params_file = f.name

    try:
        # Use neo4j driver locally via subprocess that imports neo4j
        # Since cypher-shell doesn't support params, use Python neo4j driver
        result = subprocess.run(
            ["python3", "-c", f"""
import json
import sys
sys.path.insert(0, '/opt/homebrew/lib/python3.11/site-packages')
from neo4j import GraphDatabase

with open('{params_file}') as f:
    params = json.load(f)

cypher_text = '''{cypher_text}'''

# Connect via docker bridge
driver = GraphDatabase.driver('neo4j://localhost:7687', auth=('neo4j', 'localtest12'), encrypted=False)
try:
    with driver.session() as session:
        result = session.run(cypher_text, records=params['records'])
        row = result.single()
        if row:
            print(json.dumps(row['result']))
        else:
            print('{{}}')
finally:
    driver.close()
"""],
            capture_output=True,
            text=True,
            check=False
        )
        if result.returncode != 0:
            print(f"ERROR: {result.stderr}", file=sys.stderr)
            return "{}"
        return result.stdout.strip()
    finally:
        os.unlink(params_file)


def run_cypher_docker(cypher_text: str) -> str:
    """Execute cypher via docker exec cypher-shell."""
    proc = subprocess.run(
        ["docker", "exec", "-i", "mycelium-neo4j-local", "cypher-shell",
         "-u", "neo4j", "-p", "localtest12",
         "--encryption", "false", "--format", "plain"],
        input=cypher_text,
        capture_output=True,
        text=True,
        check=False
    )
    if proc.returncode != 0:
        print(f"ERROR: {proc.stderr}", file=sys.stderr)
        return ""
    return proc.stdout


def get_before_stats() -> dict:
    """Query graph statistics before backfill."""
    cypher = """MATCH (w:Word) WITH w
WITH count(w) AS total_words,
     size([x IN collect(w) WHERE NOT x.is_stopword]) AS content_words
MATCH ()-[e:APPEARS_IN]->()
WITH total_words, content_words, count(e) AS appears_in_edges
MATCH ()-[e:CO_OCCURS]->()
RETURN total_words, content_words, appears_in_edges, count(e) AS co_occurs_edges"""

    output = run_cypher_docker(cypher)
    lines = output.strip().split("\n")
    if len(lines) < 2:
        return {"total_words": 0, "content_words": 0, "appears_in_edges": 0, "co_occurs_edges": 0}

    # Parse the data line (skip header)
    parts = lines[-1].split(",")
    if len(parts) >= 4:
        try:
            return {
                "total_words": int(parts[0].strip()),
                "content_words": int(parts[1].strip()),
                "appears_in_edges": int(parts[2].strip()),
                "co_occurs_edges": int(parts[3].strip()),
            }
        except ValueError:
            pass
    return {"total_words": 0, "content_words": 0, "appears_in_edges": 0, "co_occurs_edges": 0}


def get_top_words(limit: int = 10) -> list[dict]:
    """Get top N words by frequency."""
    cypher = f"""MATCH (w:Word) WHERE NOT w.is_stopword
RETURN w.lemma AS lemma, w.frequency AS frequency, w.surface_forms AS surfaces
ORDER BY w.frequency DESC
LIMIT {limit}"""

    output = run_cypher_docker(cypher)
    words = []
    lines = output.strip().split("\n")
    # Skip header (first line)
    for line in lines[1:]:
        if line.strip():
            # cypher-shell plain format: lemma,frequency,"[surface1, surface2]"
            # Simple parse: take first field as lemma, second as freq
            parts = line.split(",", 2)
            if len(parts) >= 2:
                lemma = parts[0].strip()
                try:
                    freq = int(parts[1].strip())
                    surfaces = []
                    if len(parts) >= 3:
                        surfaces_str = parts[2].strip()
                        if surfaces_str.startswith('"') and surfaces_str.endswith('"'):
                            surfaces_str = surfaces_str[1:-1]
                        surfaces_str = surfaces_str.replace('\\"', '"')
                        try:
                            surfaces = json.loads(surfaces_str)
                        except:
                            surfaces = [surfaces_str]
                    words.append({"lemma": lemma, "frequency": freq, "surfaces": surfaces})
                except ValueError:
                    pass

    return words


def main():
    parser = argparse.ArgumentParser(description="Backfill vocabulary into graph from corpus")
    parser.add_argument("--corpus-file", type=str, default="/tmp/vocab-corpus.jsonl",
                        help="Path to corpus JSONL (default /tmp/vocab-corpus.jsonl)")
    parser.add_argument("--extract", action="store_true",
                        help="Extract corpus first (run extract-vocabulary.py --corpus)")
    args = parser.parse_args()

    # Extract if requested
    if args.extract:
        print("[1/3] Extracting vocabulary corpus...", file=sys.stderr)
        mycelium_root = os.path.join(os.path.dirname(__file__), "../..")
        with open(args.corpus_file, 'w') as out:
            result = subprocess.run(
                ["python3", os.path.join(mycelium_root, "graph/runner/extract-vocabulary.py"), "--corpus"],
                stdout=out,
                stderr=subprocess.PIPE,
                text=True,
                check=True
            )
            if result.stderr:
                print(f"  -> {result.stderr.strip()}", file=sys.stderr)

    # Load records
    print(f"[2/3] Loading records from {args.corpus_file}...", file=sys.stderr)
    records = load_records(args.corpus_file)
    if not records:
        print("ERROR: No records to backfill", file=sys.stderr)
        sys.exit(1)
    print(f"  -> Loaded {len(records)} records", file=sys.stderr)

    # Get before stats
    print("[3/3] Backfilling into graph (calling protocol)...", file=sys.stderr)
    before = get_before_stats()
    print(f"  Before: {before['content_words']} content words, {before['appears_in_edges']} APPEARS_IN edges",
          file=sys.stderr)

    # Execute protocol with all records at once
    start_time = time.time()
    protocol_path = os.path.join(os.path.dirname(__file__), "../protocols/vocabulary-backfill.cypher")
    with open(protocol_path) as f:
        protocol_cypher = f.read()

    # Try using neo4j driver directly
    result_json = run_cypher_with_params(protocol_cypher, {"records": records})
    try:
        result = json.loads(result_json) if result_json and result_json != "{}" else {}
    except:
        result = {}

    elapsed = time.time() - start_time

    # Get after stats
    after = get_before_stats()
    top_words = get_top_words(10)

    # Report
    print("\n" + "=" * 80, file=sys.stderr)
    print("BACKFILL COMPLETE", file=sys.stderr)
    print("=" * 80, file=sys.stderr)
    print(f"Elapsed: {elapsed:.1f}s", file=sys.stderr)
    print(f"\nWord Nodes:", file=sys.stderr)
    print(f"  Before: {before['total_words']} total, {before['content_words']} content", file=sys.stderr)
    print(f"  After:  {after['total_words']} total, {after['content_words']} content", file=sys.stderr)
    print(f"  Created: {after['content_words'] - before['content_words']} new content words", file=sys.stderr)
    print(f"\nAPPEARS_IN Edges:", file=sys.stderr)
    print(f"  Before: {before['appears_in_edges']}", file=sys.stderr)
    print(f"  After:  {after['appears_in_edges']}", file=sys.stderr)
    print(f"  Created: {after['appears_in_edges'] - before['appears_in_edges']}", file=sys.stderr)
    print(f"\nCO_OCCURS Edges:", file=sys.stderr)
    print(f"  Before: {before['co_occurs_edges']}", file=sys.stderr)
    print(f"  After:  {after['co_occurs_edges']}", file=sys.stderr)
    print(f"  Created: {after['co_occurs_edges'] - before['co_occurs_edges']}", file=sys.stderr)
    print(f"\nTop 10 Content Words by Frequency:", file=sys.stderr)
    for j, w in enumerate(top_words, 1):
        print(f"  {j:2d}. {w['lemma']:20s} {w['frequency']:4d}x  {w['surfaces']}", file=sys.stderr)

    # JSON output for scripting
    output = {
        "elapsed_ms": int(elapsed * 1000),
        "records_processed": len(records),
        "words": {
            "before": before['total_words'],
            "after": after['total_words'],
            "content_before": before['content_words'],
            "content_after": after['content_words'],
            "created": after['content_words'] - before['content_words'],
        },
        "appears_in_edges": {
            "before": before['appears_in_edges'],
            "after": after['appears_in_edges'],
            "created": after['appears_in_edges'] - before['appears_in_edges'],
        },
        "co_occurs_edges": {
            "before": before['co_occurs_edges'],
            "after": after['co_occurs_edges'],
            "created": after['co_occurs_edges'] - before['co_occurs_edges'],
        },
        "top_words": top_words,
    }
    print(json.dumps(output, indent=2))


if __name__ == "__main__":
    main()
