// @node_id: schema-repofile
// @label: "RepoFile Schema"
// @kind: schema
// @description: Constraints and indexes for :RepoFile nodes (meta-tracking of repo files for self-scaffolding — Track I wi-gs-11)
// ============================================================================
// wi-gs-11: :RepoFile schema + constraints + indexes
//
// RepoFile is a meta-node representing every file tracked in the repo that belongs
// to the "Meta-only" category: external tools consume these files; the graph holds
// a :RepoFile node documenting what the file is, who consumes it, and how it relates
// to graph content.
//
// File categories (design principle from plan § File SoT categories):
//   - Content-in-graph: Graph holds the bytes (e.g., graph/plans/*.cypher)
//   - Projection-of-graph: Graph is SoT; file is autogenerated (e.g., README.md)
//   - Meta-only: External tool consumes file; :RepoFile holds the meta (e.g., cmd/maverick/main.go)
//
// Every :RepoFile node:
//   - Has a stable, unique path (normalized, absolute from repo root)
//   - Records sha (git commit hash of the file's last change)
//   - Declares its category (one of the three above)
//   - Lists which systems consume it (compiler, docker, systemd, github-actions, installer-bootstrap, git-transport, etc.)
//   - Optionally documents relationships: ENFORCES invariant, PROJECTED_FROM graph content, DEPENDS_ON other files
//
// Usage:
//   - CI drift-check: walk all :RepoFile nodes, verify each path exists and sha matches current HEAD
//   - Self-scaffolding: graph-native manifest of what files matter and why
//   - Healing: if a file drifts, :RepoFile metadata guides the correction (e.g., re-export if Projection-of-graph)
// ============================================================================

// --- CONSTRAINT: Unique path on :RepoFile nodes ---
// Every file path in the repo is unique. Path is normalized (no trailing slash,
// absolute from repo root, forward slashes). Re-ingestion with the same path
// updates the sha and other properties via MERGE (idempotent).

CREATE CONSTRAINT repofile_path_unique IF NOT EXISTS
  FOR (r:RepoFile) REQUIRE r.path IS UNIQUE;

// --- INDEX: sha (git commit hash) for version tracking ---
// Supports queries identifying which files changed in a given commit:
//   MATCH (r:RepoFile {sha: 'abc123...'}) RETURN r.path
// Used by drift-check CI job and audit trails.

CREATE INDEX repofile_sha_index IF NOT EXISTS
  FOR (r:RepoFile) ON (r.sha);

// --- INDEX: category for file classification ---
// Supports filtering by category (content-in-graph, projection-of-graph, meta-only):
//   MATCH (r:RepoFile {category: 'meta-only'}) RETURN r.path
// Enables category-specific healing (e.g., re-export all projection-of-graph files).

CREATE INDEX repofile_category_index IF NOT EXISTS
  FOR (r:RepoFile) ON (r.category);

// --- COMPOSITE INDEX: (consumed_by) for tool-centric dependency analysis ---
// Supports efficient filtering by which systems consume each file:
//   MATCH (r:RepoFile) WHERE 'compiler' IN r.consumed_by RETURN r
// Answers "which files does Docker consume?" or "rebuild plan for GitHub Actions changes".
// consumed_by is a list of strings like ['compiler','docker','systemd','installer-bootstrap'].

CREATE INDEX repofile_consumed_by_index IF NOT EXISTS
  FOR (r:RepoFile) ON (r.consumed_by);

// ============================================================================
// SCHEMA PROPERTIES ON :RepoFile NODES
// ============================================================================
//
// When a :RepoFile node is created (or updated), it includes:
//
//   - path (required, unique): Normalized file path from repo root.
//          Type: String
//          Format: no leading slash, no trailing slash, forward slashes, absolute from repo root
//          Example: 'cmd/maverick/main.go', '.github/workflows/release.yml', 'install.sh'
//          Case: as-is from filesystem (Git tracks case-sensitively on non-Mac)
//          Used for: drift-check validation ("does this file exist?"), self-scaffolding
//
//   - category (required): One of three SoT categories.
//          Type: String, one of: 'content-in-graph', 'projection-of-graph', 'meta-only'
//          Examples:
//            - 'content-in-graph': 'graph/schemas/repofile.cypher' (this file)
//            - 'projection-of-graph': 'README.md' (generated from :ContributorGuide + :Plan + graph metadata)
//            - 'meta-only': 'cmd/maverick/main.go' (external Go compiler consumes it)
//          Used for: healing strategy (e.g., meta-only → check exists; projection → regenerate from graph)
//
//   - sha (required): Git commit hash of the file's last change.
//          Type: String (40-char hex SHA-1 from `git rev-parse HEAD:<path>`)
//          Used for: drift detection (if file changed, sha changes), version tracking
//          Example: 'abc123def456...'
//
//   - consumed_by (required): List of systems that use this file.
//          Type: List of Strings
//          Examples:
//            - ['compiler'] for Go source files (Go toolchain)
//            - ['docker'] for docker-compose.yml (Docker engine)
//            - ['systemd'] for .service files (systemd init system)
//            - ['github-actions'] for .github/workflows/*.yml (GitHub CI)
//            - ['installer-bootstrap'] for install.sh, install.ps1 (bootstrap script)
//            - ['git-transport'] for .gitignore, .gitattributes (Git itself)
//            - ['npm'] for package.json, go.mod (package managers)
//            - Multi-consumers: e.g., ['docker', 'systemd'] for Dockerfile deployed via systemd
//          Used for: dependency analysis (e.g., "if bot/*.go changes, rebuild Docker image")
//
//   - description (optional): Human-readable summary of the file's role.
//          Type: String
//          Example: 'Main entry point for maverick binary; handles CLI dispatch'
//          Example: 'Workflow for releasing binaries to GitHub (runs on tag push)'
//
//   - last_verified (optional): ISO 8601 timestamp when drift-check last verified this file existed.
//          Type: DateTime
//          Used for: monitoring verification frequency, alerting on stale checks
//
//   - node_id (optional): Stable idempotency key for MERGE.
//          Type: String (format: "repofile-<normalized-path>")
//          Example: 'repofile-cmd-maverick-main.go'
//          Allows safe re-ingestion without duplicates; used by manifest apply.
//
// ============================================================================
// DOCUMENTED RELATIONSHIPS
// ============================================================================
//
// A :RepoFile node may have edges to other graph nodes. These relationships
// document structural dependencies and invariants:
//
//   - [:ENFORCES] -> :Invariant
//     Meaning: This file enforces a specific invariant.
//     Example: 'graph/invariants/admin-writes-forbidden.cypher' -[:ENFORCES]-> (:Invariant {name: 'admin-writes-forbidden'})
//     Used by: invariant-validation, healing protocols
//
//   - [:PROJECTED_FROM] -> <content-node>
//     Meaning: This file is autogenerated from graph content.
//     Example: 'README.md' -[:PROJECTED_FROM]-> (:ContributorGuide)
//             'CONTRIBUTING.md' -[:PROJECTED_FROM]-> (:ContributorGuide)
//     Used by: CI drift-check (file should match graph-projected output)
//             healing (if drift, regenerate from source)
//
//   - [:DEPENDS_ON] -> :RepoFile
//     Meaning: This file depends on another file being present (e.g., import, include, reference).
//     Example: 'install.sh' -[:DEPENDS_ON]-> (:RepoFile {path: '.goreleaser.yaml'})
//             'docker-compose.yml' -[:DEPENDS_ON]-> (:RepoFile {path: 'cmd/maverick/main.go'})
//     Used by: rebuild planning (if dependency changes, what needs to rebuild?)
//
//   - [:GENERATED_BY] -> :Protocol
//     Meaning: A protocol generates this file.
//     Example: 'README.md' -[:GENERATED_BY]-> (:Protocol {name: 'export-guide'})
//     Used by: healing automation (if file is lost, which protocol regenerates it?)
//
// ============================================================================

// --- Summary Report ---
RETURN
  'RepoFile schema + constraints + indexes loaded (wi-gs-11)' AS status;
