#!/usr/bin/env python3
"""
contribute.py — Graph-native contribution driver

Reads :MergeRule nodes from a Neo4j target and fires them to extract novelty and
emit cypher files ready to PR. The driver is rule-based: each rule declares WHAT
counts as novel, HOW to detect it, and WHERE to emit it.

Rule schema: :MergeRule {node_id, project, priority, kind, detect_cypher, novelty_mode,
item_key, fetch_cypher (nullable), ship_dir, ship_filename, ship_body, rationale,
scope_default, fire_count}

Novelty modes:
  - 'in-local-not-in-dev': run detect_cypher on both local and dev; emit novel items
  - 'property-drift': compare property sets per shared label; emit drift findings only
  - 'report-only': summarize findings to manifest, no files emitted

Usage:
    python3 scripts/contribute.py [--out <dir>] [--rules-from dev|local] [--rule <id>] [--dry-run]

Environment:
    NEO4J_BOLT       local Neo4j endpoint (default: bolt://localhost:7687)
    NEO4J_USER       local user (default: neo4j)
    NEO4J_PASS       local password (default: localtest12)
    DEV_BOLT         dev Neo4j endpoint (default: bolt://5.78.206.137:7698)
    DEV_USER         dev user (default: team)
    DEV_PASS         read from ~/.mycelium/secrets.env via source
    MYCELIUM_DEV_PASS env var with dev password

Templating:
    ship_filename and ship_body support Python str.format placeholders.
    Use {{ and }} for literal cypher braces (e.g., {{foo: 'bar'}}).
    Context dict includes: item, slug, {label}, {nid}, rule.scope_default fields.

Auto-generated file header format:
    // @node_id: <derived>
    // @label: "<derived>"
    // @kind: knowledge|protocol|fixtures
    //
    // Auto-generated by scripts/contribute.py on <ts>
    // Rule: <rule.node_id>
    // ============================================================================
"""

import argparse
import os
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

try:
    from neo4j import GraphDatabase
except ImportError:
    print("ERROR: pip install neo4j", file=sys.stderr)
    sys.exit(1)

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = REPO_ROOT

NEO4J_BOLT = os.environ.get("NEO4J_BOLT", "bolt://localhost:7687")
NEO4J_USER = os.environ.get("NEO4J_USER", "neo4j")
NEO4J_PASS = os.environ.get("NEO4J_PASS", "localtest12")

DEV_BOLT = os.environ.get("DEV_BOLT", "bolt://5.78.206.137:7698")
DEV_USER = os.environ.get("DEV_USER", "team")
DEV_PASS = os.environ.get("MYCELIUM_DEV_PASS", "")


def get_dev_password():
    """Load DEV_PASS from ~/.mycelium/secrets.env if not in env."""
    global DEV_PASS
    if DEV_PASS:
        return DEV_PASS
    secrets_file = Path.home() / ".mycelium" / "secrets.env"
    if secrets_file.exists():
        try:
            out = subprocess.check_output(
                ["bash", "-c", f"source {secrets_file} && echo \"$MYCELIUM_DEV_PASS\""],
                text=True
            ).strip()
            return out
        except Exception:
            pass
    return ""


def connect_local():
    """Connect to local Neo4j."""
    try:
        driver = GraphDatabase.driver(NEO4J_BOLT, auth=(NEO4J_USER, NEO4J_PASS))
        driver.verify_connectivity()
        return driver
    except Exception as e:
        print(f"ERROR: Cannot connect to local Neo4j at {NEO4J_BOLT}: {e}", file=sys.stderr)
        sys.exit(1)


def connect_dev():
    """Connect to dev Neo4j."""
    dev_pass = get_dev_password()
    if not dev_pass:
        print(f"ERROR: DEV_PASS not found. Set MYCELIUM_DEV_PASS or ~/.mycelium/secrets.env", file=sys.stderr)
        sys.exit(1)
    try:
        driver = GraphDatabase.driver(DEV_BOLT, auth=(DEV_USER, dev_pass))
        driver.verify_connectivity()
        return driver
    except Exception as e:
        print(f"ERROR: Cannot connect to dev Neo4j at {DEV_BOLT}: {e}", file=sys.stderr)
        sys.exit(1)


def fetch_rules(driver, order_by_priority=True):
    """Fetch all MergeRule nodes, optionally ordered by priority."""
    with driver.session() as session:
        query = """
        MATCH (r:MergeRule)
        RETURN r ORDER BY
          CASE r.priority
            WHEN 'highest' THEN 0
            WHEN 'high' THEN 1
            WHEN 'medium' THEN 2
            WHEN 'low' THEN 3
            ELSE 4 END,
          r.node_id
        """
        result = session.run(query)
        rules = []
        for record in result:
            r = record["r"]
            rules.append({
                "node_id": r.get("node_id"),
                "project": r.get("project"),
                "priority": r.get("priority"),
                "kind": r.get("kind"),
                "detect_cypher": r.get("detect_cypher"),
                "novelty_mode": r.get("novelty_mode"),
                "item_key": r.get("item_key"),
                "fetch_cypher": r.get("fetch_cypher"),
                "ship_dir": r.get("ship_dir"),
                "ship_filename": r.get("ship_filename"),
                "ship_body": r.get("ship_body"),
                "rationale": r.get("rationale"),
                "scope_default": r.get("scope_default"),
            })
        return rules


def run_query(driver, cypher, params=None):
    """Execute cypher and return result rows as list of dicts."""
    with driver.session() as session:
        result = session.run(cypher, parameters=params or {})
        rows = []
        for record in result:
            rows.append(dict(record))
        return rows


def make_slug(text):
    """Convert text to slug: lowercase, non-alnum to hyphens, strip edges."""
    return re.sub(r"[^a-z0-9]+", "-", str(text).lower()).strip("-")


def _escape_cypher_string(s):
    """Escape a Python value for safe interpolation into a single-quoted
    Cypher string literal."""
    if s is None:
        return ""
    s = str(s)
    return s.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")


def _render_fixture_merges(rows, label, scope):
    """Render 3 sample nodes as idempotent MERGE blocks."""
    out = []
    for i, row in enumerate(rows[:3]):
        nid = row.get("node_id") or f"example-{make_slug(label)}-{i}"
        props = {k: v for k, v in row.items() if v is not None}
        props.setdefault("project", scope)
        props["node_id"] = nid
        pairs = []
        for k, v in sorted(props.items()):
            if isinstance(v, bool):
                val = "true" if v else "false"
            elif isinstance(v, (int, float)):
                val = str(v)
            elif isinstance(v, (list, tuple)):
                items = ", ".join(f"'{_escape_cypher_string(x)}'" for x in v)
                val = f"[{items}]"
            else:
                val = f"'{_escape_cypher_string(v)[:240]}'"
            pairs.append(f"{k}: {val}")
        out.append(f"MERGE (n:{label} {{node_id: '{_escape_cypher_string(nid)}'}})\nSET n += {{{', '.join(pairs)}}};\n")
    return "\n".join(out)


class _DefaultEmpty(dict):
    """Dict that returns '' for missing keys — used with str.format_map so
    templates degrade gracefully instead of stripping all placeholders."""
    def __missing__(self, key):
        return ""


def render_template(template, context):
    """Render template with context.

    {{ }} render as literal braces, { } are placeholders.
    Missing placeholders render as empty string (not KeyError).
    """
    return template.format_map(_DefaultEmpty(context))


def write_file(path, header_comment, body, dry_run=False):
    """Write file with auto-generated header."""
    path.parent.mkdir(parents=True, exist_ok=True)
    content = header_comment + "\n" + body
    if not dry_run:
        with open(path, "w") as f:
            f.write(content)
    return path


def main():
    parser = argparse.ArgumentParser(description="Graph-native contribution driver")
    parser.add_argument("--out", default=str(DEFAULT_OUT), help="Output directory (default: repo root)")
    parser.add_argument("--rules-from", default="dev", choices=["dev", "local"], help="Where to read rules from")
    parser.add_argument("--rule", default=None, help="Fire only one rule by node_id")
    parser.add_argument("--dry-run", action="store_true", help="Print what would be written, don't write")
    args = parser.parse_args()

    out_dir = Path(args.out)
    local_driver = connect_local()
    # dev_driver is always the shared dev (for diff), regardless of --rules-from
    dev_driver = connect_dev()
    rules_driver = dev_driver if args.rules_from == "dev" else local_driver

    try:
        # Fetch rules
        rules = fetch_rules(rules_driver)
        if args.rule:
            rules = [r for r in rules if r["node_id"] == args.rule]

        if not rules:
            print("0 rules found")
            return 0

        fired = 0
        emitted = []
        property_drift_findings = {}

        for rule in rules:
            rule_id = rule["node_id"]
            detect = rule["detect_cypher"]
            mode = rule["novelty_mode"]
            item_key = rule["item_key"]
            fetch = rule["fetch_cypher"]
            ship_dir = rule["ship_dir"]
            filename_template = rule["ship_filename"]
            body_template = rule["ship_body"]

            if not detect or not mode:
                continue

            # Detect candidates locally
            try:
                local_items = run_query(local_driver, detect)
            except Exception as e:
                print(f"  Rule {rule_id}: detect_cypher error: {e}", file=sys.stderr)
                continue

            # Novelty filter
            novel_items = []
            if mode == "in-local-not-in-dev":
                try:
                    dev_items = run_query(dev_driver, detect)
                    dev_keys = {item.get(item_key) for item in dev_items}
                    novel_items = [item for item in local_items if item.get(item_key) not in dev_keys]
                except Exception as e:
                    print(f"  Rule {rule_id}: dev comparison error: {e}", file=sys.stderr)
                    novel_items = local_items

            elif mode == "property-drift":
                # Compare property sets; emit to manifest only
                property_drift_findings[rule_id] = {"local": len(local_items), "novel": True}
                novel_items = []  # Don't emit files for property-drift

            elif mode == "report-only":
                novel_items = []

            # Emit files
            for item in novel_items:
                item_val = item.get(item_key)
                context = {
                    "item": item_val,
                    "slug": make_slug(item_val),
                    **item,  # Include all item fields as {name} placeholders
                }

                # Fetch additional data if needed. Rules use <item> as a
                # string-replace placeholder (not $item parameter) because
                # backticks + parameters don't mix for dynamic labels.
                if fetch:
                    try:
                        # Substitute <item> in the fetch cypher string
                        fetch_resolved = fetch.replace("<item>", str(item_val))
                        fetch_rows = run_query(local_driver, fetch_resolved)
                        if fetch_rows:
                            # Spread fetch columns into context; compute useful
                            # derived fields for the common templates
                            context.update(fetch_rows[0])
                            # Cypher-literal list for properties (so it
                            # renders as ['a','b'] in MERGE body)
                            props = context.get("properties")
                            if isinstance(props, (list, tuple)):
                                context["properties_cypher_list"] = (
                                    "[" + ", ".join(f"'{p}'" for p in props) + "]"
                                )
                            # For sample_rows (fixtures): render each as a MERGE
                            rows = context.get("sample_rows")
                            if isinstance(rows, list):
                                context["fixture_merges"] = _render_fixture_merges(
                                    rows, item_val, rule.get("scope_default", "maverick-dev-friend")
                                )
                            # Escape commonly-referenced string fields so
                            # they're safe to interpolate into single-quoted
                            # Cypher literals
                            for k in ("label", "rationale", "claim", "verify_cypher",
                                      "check_cypher", "heal_protocol", "severity",
                                      "status", "body"):
                                if k in context and context[k] is not None:
                                    context[f"{k}_escaped"] = _escape_cypher_string(context[k])
                            # Fallbacks for rules that reference foo_or_bar
                            context.setdefault("severity_or_medium", context.get("severity") or "medium")
                            context.setdefault("heal_protocol_or_none", context.get("heal_protocol") or "none")
                            context.setdefault("status_or_active", context.get("status") or "active")
                            # Protocol body passthrough
                            if context.get("body"):
                                context["body_or_synthesized"] = context["body"]
                            else:
                                context["body_or_synthesized"] = (
                                    f"// @node_id: {item_val}\n// auto-synthesized placeholder\n"
                                )
                            # Typical shapes list for rel-type rule
                            ts = context.get("typical_shapes")
                            if isinstance(ts, list):
                                context["typical_shapes_repr"] = (
                                    "["
                                    + ", ".join(
                                        f"'{s.get('src','?')}-[{item_val}]->{s.get('tgt','?')} ({s.get('count',0)})'"
                                        for s in ts
                                    )
                                    + "]"
                                )
                    except Exception as e:
                        print(f"  Rule {rule_id} item {item_val}: fetch error: {e}", file=sys.stderr)

                # Render paths and body
                try:
                    rendered_filename = render_template(filename_template, context)
                    rendered_body = render_template(body_template, context)
                except Exception as e:
                    print(f"  Rule {rule_id} item {item_val}: template error: {e}", file=sys.stderr)
                    continue

                output_path = out_dir / ship_dir / rendered_filename
                nid = context.get("node_id", rule_id)
                label = context.get("label", item_val)
                header = f"""// @node_id: {nid}
// @label: "{label}"
// @kind: {rule.get("kind", "knowledge")}
//
// Auto-generated by scripts/contribute.py on {datetime.utcnow().isoformat()}
// Rule: {rule_id}
// ============================================================================"""

                write_file(output_path, header, rendered_body, args.dry_run)
                emitted.append({
                    "rule_id": rule_id,
                    "item": item_val,
                    "path": str(output_path),
                    "dir": ship_dir
                })

            fired += 1
            if not args.dry_run or novel_items:
                print(f"  {rule_id}: detected {len(local_items)} items, {len(novel_items)} novel")

        # Write manifest
        ts = datetime.utcnow().isoformat()
        manifest_lines = [
            "# Contribution Manifest",
            f"Timestamp: {ts}",
            "",
            f"## Execution",
            f"- Rules fired: {fired}",
            f"- Files emitted: {len(emitted)}",
            f"- Dry run: {args.dry_run}",
            "",
            "## Emitted Files",
        ]
        for e in emitted:
            manifest_lines.append(f"- [{e['rule_id']}] {e['item']} → {e['path']}")

        if property_drift_findings:
            manifest_lines.append("")
            manifest_lines.append("## Property Drift Findings")
            for rid, finding in property_drift_findings.items():
                manifest_lines.append(f"- {rid}: {finding['local']} items detected (see graph/contribution-manifest.md)")

        manifest_path = out_dir / "graph" / "contribution-manifest.md"
        manifest_content = "\n".join(manifest_lines)
        write_file(manifest_path, "", manifest_content, args.dry_run)

        # Write ContributionRun cypher snippet
        cr_node_id = f"contribution-run-{ts.replace(':', '-')[:19]}"
        cr_cypher = f"""// @node_id: {cr_node_id}
// @label: "Contribution Run {ts}"
// @kind: system

MERGE (cr:ContributionRun {{node_id: '{cr_node_id}'}})
SET cr.timestamp = '{ts}',
    cr.rules_fired = {fired},
    cr.files_emitted = {len(emitted)},
    cr.dry_run = {str(args.dry_run).lower()}
RETURN cr;
"""
        cr_path = out_dir / "graph" / "knowledge" / f"contribution-run-{ts.replace(':', '-')[:19]}.cypher"
        write_file(cr_path, "", cr_cypher, args.dry_run)

        print(f"{fired} rules fired, {len(emitted)} files emitted under graph/{{knowledge,protocols,fixtures}}")
        print(f"see {manifest_path} for decision log")
        return 0

    finally:
        local_driver.close()
        dev_driver.close()
        if rules_driver not in (local_driver, dev_driver):
            rules_driver.close()


if __name__ == "__main__":
    sys.exit(main())
